### ISSUE TITLE
[TONE][KAGURA]Microphone is not calibrated correctly

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#123]
Platform:Tone
Device:Kagura (possibly more)
Kernel version:4.4
Android version:All supported

Description:
Microphone issue in media app

Symptoms:
The microphone sensitivity is too low for day to day situations, VOiP calls are difficult because you have to stick your mouth to the mic to get understood.
Voice on call is a bit too low too but not as much as above.

How to reproduce:
Record a media file with the mic (eg; Snapchat, Video with camera app, voice recorder)

**Comment by richardtullberg** [comment]
Hi,

have you checked these patches if they fix the issue?
https://github.com/sonyxperiadev/device-sony-suzu/pull/49
https://github.com/sonyxperiadev/device-sony-suzu/pull/51

It's both for camera and for voip and everyone that uses the handset dual mic

BR Richard

**Comment by oshmoun** [comment]
would the exact same changes apply for tone,or are changes in ctl names/values required?

**Comment by richardtullberg** [comment]
Well, I checked in my list of settings and Tone and Loire has the same routing. So the same changes should be correct to apply.
What might not be correct is this:
Camcorder routing might be different. I see something funny here that in Tone the routing is "camcorder-mic" while on Loire it is "handset-stereo-dmic-ef". The Loire routing is the correct one, so I will have to check whats going on in Tone.
The microphone gains might need to be changed, but that should be the case for each "product" since the hardware changes.

**Comment by Paulbouchara** [comment]
https://github.com/sonyxperiadev/device-sony-kagura/pull/34
Fixies the issue, thanks for your time !
