### ISSUE TITLE
Xperia XA2 - USB Tethering stops working while mobile data is active and wifi is restarted 

### ISSUE THREAD

**Issue by dimitar10** [sonyxperiadev/bug_tracker#147]
**Platform:** nile
**Device:** pioneer (H4113)
**Kernel version:** 4.4.140-gdc5bc38
**Android version:** 8.1.0-r35
**Firmware version:** v14

**Description**
- USB tethering breaks down when both wifi and mobile data are active, the option 'Mobile Data Always On' is switched off by default, and wifi is switched off and then on by the user.

**Symptoms**
- USB tethering breaks down and the user loses internet access on the tethered PC

**How to reproduce**

In Developer options, 'Mobile data always active' is OFF by default. WiFi and Mobile data are enabled.

1. Reboot device
1. Connect the device to a PC via USB
1. Turn USB tethering ON (10:10)
1. Browse sites on the PC - OK
1. Turn WiFi OFF (10:11) 
1. Browse sites on the PC - OK
1. Turn WiFi ON (10:11)
1. Browse sites on the PC - NOK

**Discussion** Possible impact on bluetooth tethering as well, but not tested as of yet

**Logs** logcat, dmesg are included. The output from ip rule list and ip tables included are after losing tethering.

[xa2-usb-tethering-issue-20180726.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2231244/xa2-usb-tethering-issue-20180726.tar.gz)

**Comment by aolexiy** [comment]
This is fixed by following CAF commits, could you, please, double-check it on your side? Also, you seem to be using Windows host, is that correct?

1) https://source.codeaurora.org/quic/la/platform/frameworks/base/patch/services/core/java/com/android/server/connectivity/tethering/UpstreamNetworkMonitor.java?id=f2528c4688eb6f3993298b9df73b115756950494

2) https://source.codeaurora.org/quic/la/platform/frameworks/base/patch/services/core/java/com/android/server/connectivity/tethering/UpstreamNetworkMonitor.java?id=047796df15205e4d6758485e708e35e90634afe4

3) https://source.codeaurora.org/quic/la/platform/frameworks/base/patch/services/core/java/com/android/server/connectivity/tethering/UpstreamNetworkMonitor.java?id=1d2589fe9ab85c64478ff2b215ec0a7a64d5d81b

Ref. log (3 commits on top) - https://source.codeaurora.org/quic/la/platform/frameworks/base/log/services/core/java/com/android/server/connectivity/tethering/UpstreamNetworkMonitor.java?h=android-framework.lnx.3.1.r4-rel

**Comment by dimitar10** [comment]
Thank you very much, applying the suggested commits fixed the issue. I used both Windows 7 and Ubuntu 18.04, and the behaviour was the same. I think the logs were pulled when the the XA2 was connected to the Ubuntu.
