### ISSUE TITLE
[Tama] - Android 8.1r46 - Several Bugs

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#169]
My builds:
[https://forum.xda-developers.com/xperia-xz2/development/aosp-aosp-8-1-h8266-t3843269](https://forum.xda-developers.com/xperia-xz2/development/aosp-aosp-8-1-h8266-t3843269)
PS: I know that the XZ2 is still not an official part of the open devices programm, even, with the new bootloader v60. :)

**Platform** : tama
**Device** : akari
**Kernel**  version: 4.9
**Android**  version: 8.1r46

- **Kernel could damage display** (old builds on xda won't do it?)
- The touchscreen is not working as expected, it's picked up as a touchpad.
The UI is navigated with mouse
- It seems that the graphics acceleration is not working (gralloc?)
The display can appear to be "slow" (stuttering, low fps anyway) because of a bug with the userspace libraries on the clock calculation code. The same bug may prevent (does prevent, on SoMC Apollo DSDS) the display to resume from sleep with DSI UNDERFLOW errors. The solution to this resides in the userspace libsdedrm/libdisplayqos and HAL (has to forcefully match with blobs);
- Brightness is not adjustable.
Brightness controls are fixed after @kholk  PR on the Lights HAL and tama-common on Android. @alviteri extended the solution to healthd for other purposes.
- RIL works(sort of)
- Calls work (mic produces robotic sound)
- Developer Options menu crashes the settings app
- Sleep not working
The device sleep issues are due to general misconfiguration, we had this back in the day on Loire, Tone, Nile and Yoshino. It's due to the fact that we are integrating not yet supported things in userspace (like camera, mainly) that will keep getting killed and restarting, preventing deep sleep (or any kind of sleep);
- Device gets quite hot over timE
- Camera is not accessible(just gray screen with the navbar at the bottom)
- The SDCard is not mounted

Fixed:
- ADB is not working
- Bluetooth not working

Already works:
- Data works
- Media storage USB mode works as well.
- Sound works

**Comment by fl3x1324** [comment]
Media storage USB mode works as well.

**Comment by kholk** [comment]
I'm sorry, I don't know that, but you shouldn't use the 9.0 ODM with Android 8.1!

**Comment by MartinX3** [comment]
@kholk 
Thank you and sorry!
"For all devices: Updated data/vendor paths, updated permissions, and improved compatibility with Android 9."
confused me.
I thought the OEM is now better compatible with Android 9 and backward compatible to 8.1, too.
But good to know!

**Comment by kholk** [comment]
No problem man.

**Comment by kholk** [comment]
PLEASE DON'T FLASH TAMA WITH THE CURRENT KERNEL

My Akari's display got permanently damaged.
I repeat, DO NOT FLASH.

**Comment by MartinX3** [comment]
Thank you for this important response!!!!

Will you open a bug issue ticket, so we can see, when it is fixed?

**Comment by kholk** [comment]
You will know when this gets fixed, in a way or another, don't worry.

**Comment by MartinX3** [comment]
@kholk 
I hope, that I don't disturb you

Is it safe to compile a new kernel in 7 hours or should I wait until next week?

**Comment by kholk** [comment]
I hope to be (and should be) able to fix everything before the weekend, as I'll have to depart on Monday and won't be able to do anything for around 15 days.

After the latest PRs it's a lot safer, but I'd still not recommend to run it, it's still a lot risky, since I haven't totally verified that it is safe... yet.

**Comment by kholk** [comment]
So, to sum up the latest discoveries:

- The display can appear to be "slow" (stuttering, low fps anyway) because of a bug with the userspace libraries on the clock calculation code. The same bug may prevent (does prevent, on Apollo DSDS) the display to resume from sleep with DSI UNDERFLOW errors. The solution to this resides in the userspace libsdedrm/libdisplayqos and HAL (has to forcefully match with blobs);

- The device sleep issues are due to general misconfiguration, we had this back in the day on Loire, Tone, Nile and Yoshino. It's due to the fact that we are integrating not yet supported things in userspace (like camera, mainly) that will keep getting killed and restarting, preventing deep sleep (or any kind of sleep);

- Brightness controls are fixed after my PR on the Lights HAL and tama-common on Android. @alviteri extended the solution to healthd for other purposes.

- The kernel should now be safe to run, though I still don't recommend using it... since we still have display issues and I cannot be 100% sure that the power issues are solved until the whole display thing gets as well solved.


Stay tuned!

**Comment by kholk** [comment]
As I said, the kernel should be safe, but I still cannot recommend to use it, being more explainative....
We just need to get stuff sorted out in userspace so that the display can resume just fine and that's on @jerpelea.

Whenever he sorts out the userspace issue, I'm sure that he will be able to keep the device powered on for an hour to check if everything looks good, so... you probably don't have to wait until I come back, he should be able to verify that his display doesn't indeed die... though I don't know when can he start looking at this.

Have a lil patience, everything will get sorted out asap!

**Comment by MartinX3** [comment]
Thank you very much for this clear answer. :)
I like a transparent development cycle, so I can be patient without any problems. :)

**Comment by jerpelea** [comment]
please open separate tickets for each bug so that we can have a good overview and way forward

Thanks for keeping the bug list for tama

**Comment by jerpelea** [comment]
for the moment if you can just post those bugs in separate tickets that will be great

**Comment by MartinX3** [comment]
I am finish. :)
