### ISSUE TITLE
[Tama] - Android 8.1r46 - Developer Options menu crashes the settings app

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#185]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 8.1r46

**Description**
Developer Options menu crashes the settings app

**Symptoms**
Developer Options menu crashes the settings app

**How to reproduce**
Developer Options menu crashes the settings app

**Comment by MarijnS95** [comment]
Is this on an engineering build, and can you post a logcat?

I think this is the issue you're facing: The developer menu tries to load the `oem_lock` system service (and hide that section if it doesn't exist), but on the engineering build the log message for the missing service (`Log.wtf`) is fatal. This is unmodified AOSP code, and there's no proper way to check if a service exists. Since this service is optional, this issue should be addressed in the AOSP framework.

**Comment by MartinX3** [comment]
@fl3x1324 my nice tester? :)

**Comment by jerpelea** [comment]
working fine on an userdebug build
