### ISSUE TITLE
[all devices] replace sony keys with custom ones to enable verified boot

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/bug_tracker#195]
**Platform:**  all
**Device:**  nile
**Kernel version:** 
**Android version:** 

**Description**
Support verified boot
Would it be possible to support writing a custom key like for example with the [Pixel 2](https://android.googlesource.com/platform/external/avb/+/master/README.md#pixel-2)?

**Comment by jerpelea** [comment]
unfortunately veried boot is not suported by this platform

**Comment by MartinX3** [comment]
That's funny.
It's a brand new Oreo SMD845 Plattform, but without some nice stuff like this or RAW support. :sweat_smile:

**Comment by jerpelea** [comment]
RAW is suported by all devices

**Comment by MartinX3** [comment]
Ups, sorry.
I mean the stock ROM by Sony.
On one hand Sony is missing a software function there and on the other hand an up to date hardware feature.
There was a hardware function needed, or?

**Comment by Iolaum** [comment]
@jerpelea It's really unfortunate that android verified boot is not supported. The Sony Open devices initiative has a lot of potential. However without android verified boot and the option to relock the bootloader using custom ROM it cannot be used by projects such as GrapheneOS, RattlesnakeOS and CalyxOS. That ecosystem has been using Pixel devices because of that option (Using android verified boot and the ability to relock the bootloader with a ROM signed by custom keys. Having sources and device trees available helps as well but Sony Open devices offer that as well. Please consider allowing this option at some point. At the moment the ecosystem I mentioned is only served by Pixel devices. Admittedly it's not a big market segment but it aligns with the customers who would consider a Sony Open Device as future purchase.

**Comment by lxy0797** [comment]
any new about the issue?
It's the key feature holds me back buying experia devices

**Comment by MartinX3** [comment]
At least you can relocl newer devices now.

**Comment by mikkorantalainen** [comment]
Which Sony devices support relocking?

**Comment by MartinX3** [comment]
> Which Sony devices support relocking? I have XZ1 Compact and XZ2 Compact because those are the last high performance models with small form factor.

I think it was starting with 1/5 and 10 II

**Comment by lxy0797** [comment]
> At least you can relock newer devices now.

with custom key or just the default sony key?
