### ISSUE TITLE
[Loire] intermediate bluetooth disconnection

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#196]
**Platform:** loire
**Device:** kugo
**Kernel version:** 4.4 and 4.9
**Android version:** 8.1 and 9.0

**Description**
while playing music on a bt headset, the connection will randomly drop and playback will pause

**How to reproduce**
enable bluetooth
pair a bt headset
start music playback
after some time, and while normally using the device, bt will disconnect

**Comment by kholk** [comment]
Please post logs

**Comment by mase76** [comment]
You can find my logs here:
https://forum.xda-developers.com/showpost.php?p=77416898&postcount=512

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-common/commit/fd07d8e5399c3c384da7fe1cd126d4d9f917e68f

**Comment by oshmoun** [comment]
this is not resolved yet, still happens.
should I open a new issue or can this be re-opened?

**Comment by bartcubbins** [comment]
can confirm, this issue still persist on my suzu

**Comment by deniskuz95** [comment]
about bluetooth. sometimes it is tightly disconnected or intermittently playing music. when logging, it produces the following error: 01-28 01:02:30.366 F/linker (20127): CANNOT LINK EXECUTABLE "/odm/bin/imsdatadaemon": cannot locate symbol "dsi_query_link_local_network_handle" referenced by "/odm/bin/imsdatadaemon"...

**Comment by oshmoun** [comment]
@deniskuz95 that is an unrelated issue, and should be handled already. If you flash a clean build you should not see that error anymore, since that service has been removed.

**Comment by kholk** [comment]
How to proceed:
1. Disable serial driver power management
If issue persists
2. Disable bluesleep power management
If issue persists 
3. That's not possible, rinse and repeat. 

Once we locate the issue in one of the two drivers, then we can do magic to fix it.

**Comment by deniskuz95** [comment]
@kholk Thanks :) the problem is that I don’t know how to do it, I didn’t find instructions on the Internet ...

**Comment by kholk** [comment]
Don't worry, everyone learns.
If that's out of your skills, me, Obi or other developers can look at it.

**Comment by mase76** [comment]
I can confirm, the issue is still there on 2 of my Suzu devices.

**Comment by mase76** [comment]
Please reopen this issue. This bug is so annoying, that it makes the usage of bluetooth headsets and speakers nearly impossible.

**Comment by djselbeck** [comment]
Besides the rebooting problem of #348 the Bluetooth connection to a BT speaker is also unstable for lilac/Yoshino.

Sometimes the music stops playing but the connection is still showed as active and then as disconnected. 

I'll try to get logs next time

**Comment by djselbeck** [comment]
[bt_audio_disconnect.txt](https://github.com/sonyxperiadev/bug_tracker/files/2953977/bt_audio_disconnect.txt)

The bt audio crash starts at:

> 03-11 20:55:43.216   624 26363 E bt_a2dp_hw: a2dp_command: A2DP COMMAND A2DP_CTRL_CMD_START error 1

**Comment by mase76** [comment]
I have the same behaviour than djselbeck. The audioplayer is still running, but the connection drops. This happens within a few seconds after starting playback. It happens with all kind of audioplayers, mostly after resuming a paused playback. Sometimes turning off and on bt helps for a while.
No problems with the 3.10 kernel used in LineageOS by Chippa.

**Comment by djselbeck** [comment]
I was listening to music for around 10 minutes before the crash

**Comment by mase76** [comment]
With the 4.9 kernel used with Android 9 ROMs, bt became completely unusable. Either the bt app crashes, or audio stops playing after just a few seconds.

**Comment by stefanhh0** [comment]
I had the same problems on Yoshino/Lilac (same device as @djselbeck)

With the switch to 4.9.162 Kernel two days ago it is now pretty stable. I was able to play music on an external via bt connected speaker and experienced neither crashes/reboots or intermediate BT disconnects. I had such symptoms a lot before that build. 

Here the build info:
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.162-g7142c8274df5
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190320.064401
**Version baseband:** 1307-7511_47.1.A.16.20

I am now building with v7 and current head and will continue testing. Would be interesting if you can confirm whether switching to kernel 4.9.162 fixes the issue for you as well.

**Comment by stefanhh0** [comment]
#### General Info

**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.162-ge1ccab69b98e
**Android version:** android-9.0.0_r34
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v7_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ2A.190305.002 eng.stefan.20190322.182352
**Version baseband:** 1307-7511_47.1.A.16.20

**Description**
With a current build, after playing some music via BT speaker, 2 BT disconnects occurred. I've attached both tombstones that have been written, the logcat output + 2 dmesg files that I have dumped right after the BT disconnect.
Since this ticket is just about BT disconnects I have posted the details about the crash in #348

#### Timeline:

**Startet to play music:**
`03-23 06:24:02.621   721  6302 D NuPlayerDriver: NuPlayerDriver(0xf08a1580) created, clientPid(6420)`
**1st BT disconnect (tombstone_07):**
`03-23 06:27:18.288  6583  6583 I crash_dump64: type=1400 audit(0.0:3760): avc: denied { search } for name="com.android.bluetooth" dev="sda66" ino=786775 scontext=u:r:crash_dump:s0 tcontext=u:object_r:bluetooth_data_file:s0 tclass=dir permissive=1`
**2nd BT disconnect (tombstone_08):**
`03-23 06:34:20.838  7007  7007 I crash_dump64: type=1400 audit(0.0:3932): avc: denied { noatsecure } for scontext=u:r:bluetooth:s0 tcontext=u:r:crash_dump:s0 tclass=process permissive=1`
**Music continued to play until a phone cash/reboot occurred, last logcat entry before crash/reboot:**
`03-23 07:16:04.331  6515  6515 V MusicFXControlPanelEffect: closeSession(android.app.ReceiverRestrictedContext@44e11d0, ch.blinkenlights.android.vanilla, 81)`

#### Files
Logcat: [logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/2999077/logcat.log)
Dmesg of 1st BT disconnect: [dmesg_06_27_tombstone_07.log](https://github.com/sonyxperiadev/bug_tracker/files/2999079/dmesg_06_27_tombstone_07.log)
Dmesg of 2nd BT disconnect: [dmesg_06_34_tombstone_08.log](https://github.com/sonyxperiadev/bug_tracker/files/2999083/dmesg_06_34_tombstone_08.log)
Tombstones: [tombstones.tar.gz](https://github.com/sonyxperiadev/bug_tracker/files/2999076/tombstones.tar.gz)

**Comment by jerpelea** [comment]
@stefanhh0 this bug report is about the loire platform which uses a different BT HW 
please open a new ticket for yoshino BT

**Comment by jerpelea** [comment]
@stefanhh0 are you building AOSP?

**Comment by stefanhh0** [comment]
Moved my post and the answer to your question as requested to #362.

**Comment by kholk** [comment]
I've just engineered a possible solution for this issue, thanks to @oshmoun isolating the producer to a specific clock.

Can you please test again with this patchset?
sonyxperiadev/kernel#1985

Thanks!

**Comment by anthonyhaussman** [comment]
@kholk I also have the Bluetooth problem on kugo/loire (on 8.1 and 9.0).
How can I test your patchset?

**Comment by oshmoun** [comment]
@anthonyhaussman it's been merged into 4.9 kernel, i.e is available for 9.0
if you make a new build with the latest kernel sources you should have the Bluetooth fix

**Comment by kholk** [comment]
@anthonyhaussman To test it on Tone, you have to take the commit that is done for msm8956-loire-common.dtsi and apply it to msm8996-tone-common.dtsi

**Comment by anthonyhaussman** [comment]
No problem @kholk.
The thing is I have never build an Android kernel until now.
I'm going to try to follow the sony procedure on https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-mainline-linux-kernel-for-xperia-devices

@oshmoun, So I can use the tag v4.9 of the Linux kernel source tree repo of Torvald?

**Comment by stefanhh0** [comment]
@anthonyhaussman 
sonyxperiadev/kernel#1985
Was merged back 2 days ago.

To do a fresh build with kernel included simply call `./repo_update.sh` followed by `rm -r rm -r kernel/sony/msm-4.9/common-kernel`

common-kernel contains the precompiled kernels, if that folder is removed then kernel is automatically being build from the sources.

**Comment by anthonyhaussman** [comment]
Work great. I have used my Bluetooth headset for more than a hour. Works great without crash.

**Comment by oshmoun** [comment]
awesome, thanks for confirming
