### ISSUE TITLE
 [TONE] [ALL] Activating wifi hotspot sometimes crashes the device

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/bug_tracker#2]
**Platform**: SoMC Tone
**Device**: ALL
**Kernel version**: 4.4.xx
**Android version**: 8.0 (/ALL)

**Description**
When activating wifi hotspot, there's a very high chance that the device will crash and hard reboot.

**How to reproduce**
Try activating/deactivating wifi hotspot multiple times.

**Comment by humberos** [comment]
https://github.com/humberos/android_external_wpa_supplicant_8/commit/c53581474d909dd446edc2031efeb32899745585

This patch (workaround) fixes the crash mentioned here. I think the problem is on bcmdhd driver which may requires the newest nl80211 net detect part (implemented for wowlan).

Anyway, it is the first approach.

Tested on kagura.
Also keyaki (confirmed by @oshmoun )

**Comment by oshmoun** [comment]
Yup, can confirm that the patch works fine.

**Comment by jerpelea** [comment]
the proper paroach would be to update the kernel

**Comment by oshmoun** [comment]
This has been properly fixed now
https://github.com/sonyxperiadev/kernel/pull/1465
