### ISSUE TITLE
[lilac] bluetooth not work anymore. android 9, oem v2

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/bug_tracker#218]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9
**Android version:** 9

**Description**
Bluetooth not work.

**Symptoms**
Bluetooth not work at all.

**How to reproduce**
Compile full firmware for lilac, flash oem v2, start your phone

Logcat --> http://pasted.co/430d99a9

**Comment by jerpelea** [comment]
I tested the BT and it seems to work fine 
please sync and rebuild

**Comment by russel5** [comment]
Yesterday, after you push new OEM files, first I'm sync sources and after that make new firmware. 
How you make your kernel, use prebuild or make it when build new firmware?
I'm use new build

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-yoshino/commit/6ad1a74e012896257d8b78afe7fa4d4245962b10
https://github.com/sonyxperiadev/device-sony-common/commit/33a17052e28cafcf1ee1b7ab447731a8cb9059ef

**Comment by jerpelea** [comment]
please open a PR for the legacy path either in out init.common.rc or send the patch to https://android.googlesource.com/platform/hardware/broadcom/libbt/

**Comment by ix5** [comment]
The old path is used in a lot of places, see:
```
system/bt/doc/properties.md
18:* ``` ro.bt.bdaddr_path ```
system/sepolicy/public/property_contexts
88:ro.bt.bdaddr_path u:object_r:exported_bluetooth_prop:s0 exact string
system/core/property_service/libpropertyinfoserializer/property_info_serializer_test.cpp
632:      {"ro.bt.bdaddr_path", "u:object_r:bluetooth_prop:s0"},
vendor/broadcom/bt-fm/brcm-uim-sysfs/uim.c
85:#define PROPERTY_BT_BDADDR_PATH         "ro.bt.bdaddr_path"
hardware/interfaces/bluetooth/1.0/default/bluetooth_address.h
32:static constexpr char PROPERTY_BT_BDADDR_PATH[] = "ro.bt.bdaddr_path";
system/sepolicy/prebuilts/api/28.0/public/property_contexts
88:ro.bt.bdaddr_path u:object_r:exported_bluetooth_prop:s0 exact string
```
So I think at least the sepolicy contexts need to be updated, no?

As I see it, libbt includes board-specific `vnd_*` files which tell libbt to `USE_CONTROLLER_BDADDR`.

`vendor/broadcom/bt-fm/brcm-uim-sysfs/uim.c:`
`define PROPERTY_BT_BDADDR_PATH         "ro.bt.bdaddr_path"` sets `PROPERTY_BT_BDADDR_PATH` which then gets passed down the stack.

Defining `ro.vendor.bt.bdaddr_path` would still be useless as it's not currently read, meaning it would have to be fixed in https://github.com/sonyxperiadev/vendor-broadcom-bt-fm.

**Solution:**
- Change `#define PROPERTY_BT_BDADDR_PATH         "ro.bt.bdaddr_path"` in bt-fm
- Add a `vnd_tone` file to libbt with `USE_CONTROLLER_BDADDR = TRUE`.

Is that the correct way?

**Comment by jerpelea** [comment]
just add the old property near the new one and submit a PR

**Comment by ix5** [comment]
Alright, will do. See https://github.com/sonyxperiadev/device-sony-common/pull/531
