### ISSUE TITLE
[Discovery] Unable to update

### ISSUE THREAD

**Issue by ploth** [sonyxperiadev/bug_tracker#291]
**Platform:** Nile
**Device:** Discovery (H3213)
**Kernel version:** 4.4
**Android version:** android-8.1.0_r35

**Description**
I'm unable to update to a newer release candidate. Currently I'm running `android-8.1.0_r35` but I want to update to `android-8.1.0_r51`. The build procedure is successful. If I understand this correctly, I can upgrade by flashing `boot, system and vendor` (img) with `fastboot` and omitting `userdata` so I don't lose my apps, settings and stuff. But the phone is unable to boot until I flash 'userdata'. An update to `android-9.0.0_r16` isn't possible either. It feels like there must be a community where I can discuss such questions.

**Symptoms**
Phone is unable to boot after flashing `boot, system, vendor` if omitting `userdata`.

**How to reproduce**
Flash `boot, system, vendor` only.

**Comment by MartinX3** [comment]
Can you use ADB?
try
adb wait-for-device
Then
adb log
While the bootloop is happen.

Maybe
Adb shell works
Then "logcat" and "dmesg" are working.

Of course you need a PC USB connection and the Android Plattform Tools with fastboot and adb.

**Comment by ploth** [comment]
Ok, then you want to have those logs? I need to wait for the weekend to have some spare time.  

Are there other ways to update (aosp) android? What is the normal way without loosing the user data every time?  

I've read about [ota updates](https://source.android.com/devices/tech/ota/tools). But it looks like that this way misses the oem binaries or isn't it necessary to flash those every time?

**Comment by MartinX3** [comment]
OTA requires an infrastructure. :)

That's the normal way.
A TWRP zip file would do the same.

Yes, the errorlog may show the cause of the error. :)

**Comment by ploth** [comment]
Would theoretically an update from 8.1 to 9.0 be possible? Or do I need to start over with an major version bump?

**Comment by MartinX3** [comment]
It's possible
But wiping the phone between is recommended

**Comment by jerpelea** [comment]
update should be possible but it is better to have a backup

**Comment by ploth** [comment]
My phone states that it is encrypted (`Settings -> Security & location -> Encryption & credentials`) That can't be a reason for not being able to update?

**Comment by ploth** [comment]
> Can you use ADB?
> try
> adb wait-for-device
> Then
> adb log
> While the bootloop is happen.
> 
> Maybe
> Adb shell works
> Then "logcat" and "dmesg" are working.
> 
> Of course you need a PC USB connection and the Android Plattform Tools with fastboot and adb.

Was on `android-8.1.0_r35` flashed `{boot, system, vendor, oem}.img` of `android-9.0.0_r30`. Unfortunately it doesn't boot. It displays the black SONY logo on a white screen. The device is not available over `adb`.

**Comment by ploth** [comment]
Ok, `android-9.0.0_r30` doesn't even boot after flashing the `userdata.img` too :(

**Comment by jerpelea** [comment]
please flash the new v5 image on the oem partition

**Comment by ploth** [comment]
Where do I find it?
[This](https://developer.sony.com/file/download/software-binaries-for-aosp-pie-android-9-0-kernel-4-9-nile/) is still v4.

**Comment by ploth** [comment]
```zsh
fastboot flash boot boot.img
fastboot flash system system.img
fastboot flash vendor vendor.img
fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v5_nile.img
```
the device is going into recovery mode. `adb` is available while in recovery but not before that. `adb logcat` states `- waiting for device -`.

**Comment by ploth** [comment]
@jerpelea the issue still persists :( I can't update the phone.

**Comment by stefanhh0** [comment]
@ploth Is it still an issue?

Since no one else is answering I'll throw in my 2 cents.
You haven't flashed the userdata, backup your data and flash all partitions including userdata again. 

If that doesn't help: 
What is the output of: `fastboot getvar version-baseband` saying? 

The latest available one seems to be: 50.1.A.13.123, however that might not be available from the flashtool. You should check with the flashtool (https://developer.sony.com/develop/open-devices/get-started/flash-tool/) if there is a newer version available than your current version-baseband. If so  upgrade using the full install (that will also wipe your data). After that, boot into the system once with inserted sim-card. After that fastboot should show the updated version-baseband.

After doing so you can try flashing asop again:
- sync your repo (`repo sync --force-sync` + `repo_update.sh`)
- in lunch choose `aosp_h3213-userdebug` 
-  `make clean && make -j <n>` 
- flash all the partitions inclusively the new V6 oem and userdata:
```
fastboot flash boot boot.img
fastboot flash system system.img
fastboot flash userdata userdata.img
fastboot flash vendor vendor.img
fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v6_nile.img
```

After doing so `adb logcat` should just work fine.

**Comment by ploth** [comment]
Thank you! I'm able to upgrade (and loosing my data) but this issue is about the upgrade method letting `userdebug` untouched which doesn't work.

PS: I don't use Windows ;)

**Comment by stefanhh0** [comment]
Okay that was my misunderstanding, you want to have that working without userdata wipe, that is a different Story then.

- Regarding loosing data: Twrp has a backup and restore function which saved me a lot of time already. 
However I don't know if restore works when upgrading to a different major, never tried it. 
- Regarding userdebug, why is that not working for you? It should just work fine...

**Comment by ploth** [comment]
> Regarding loosing data: Twrp has a backup and restore function which saved me a lot of time already.

Used that Backup functionalty already. It's great.

> However I don't know if restore works when upgrading to a different major, never tried it.

Nope, doesn't worked for me.

> Regarding userdebug, why is that not working for you? It should just work fine...

That is exactly the problem here ;)

**Comment by stefanhh0** [comment]
> > Regarding userdebug, why is that not working for you? It should just work fine...
> 
> That is exactly the problem here ;)
I thought adb logcat is just not working when the reboot hangs because you haven't flashed/wiped the userdata partition. That would then not be a problem of the userdebug build, but that would indicate that the boot process hangs/stops before adb logcat is able to connect.

**Comment by stefanhh0** [comment]
Regarding the userdata problem I am a long term android user and such problems have been around for a long time. Such problems occurred for me on different phones and on different roms (cyanogenmod, lineage, aosp, whatsoever) I think that is more a problem of android in general, it seems to store sensible settings on the userdata that break booting the phone and the upgrade procedures seems to be lacking some functionality. So we end up in that it sometimes works upgrading without wiping the userdata and it sometimes does not.

From a philosophical standpoint it is not the worst thing wiping all the userdata from time to time and restoring only that data, that is really necessary. It is just like removing all the old rubbish from your closet once in a while :-)

**Comment by ploth** [comment]
Ok, thank you :)

**Comment by stefanhh0** [comment]
@ploth Regarding windows flashtool and firmware upgrade, I've just tried newflasher and xperifirm to upgrade my phone (xz1c)... all on linux without too many problems, however it is important to delete all *.ta files and partition.zip has to be unzipped into a partition sub folder and boot.zip into a boot sub folder. 

I first tried without deleting the ta files, that was not a good idea, I had to flash via emma (windows) to recover from this mistake... 

But may be it is a little to risky for you to use it, since you don't have the flashtool fallback available?!
