### ISSUE TITLE
[tone/dora] Build errors with kernel 4.9

### ISSUE THREAD

**Issue by b1mt3** [sonyxperiadev/bug_tracker#294]
**Platform: tone** 
**Device: dora** 
**Kernel version: 4.9** 
**Android version: 8.1** 

**Description**
Build process of Oreo 8.1 with kernel 4.9 runs into errors (the snippet of the log can be found [here](https://pastebin.com/70tHir1A))

**Symptoms**
Change the kernel from 4.4 to 4.9

**How to reproduce**
Build the 8.1 with kernel 4.9 for dora-f8132.

**Comment by b1mt3** [comment]
> that's not a supported configuration, but it should be a simple fix
> check the media hal patches applied here to see which are missing
> https://github.com/sonyxperiadev/repo_update/blob/master/repo_update.sh

Thank you, @oshmoun for a prompt reply.
So, am I correct that I need to find the **necessary patches** at _android.googlesource.com/platform/hardware/qcom/media_ and add them the way the existing patches are applied inside repo_update.sh?

**Comment by MarijnS95** [comment]
@b1mt3 Did you change `TARGET_KERNEL_VERSION` in the device tree to `4.4`?
Assuming you have ran `repo_update.sh` and thus have [this](https://android-review.googlesource.com/c/platform/hardware/qcom/media/+/813054) patch, that seems most likely since the code in the error messages show the `4.9` parts from the preprocessor guards.

**Comment by b1mt3** [comment]
> @b1mt3 Did you change `TARGET_KERNEL_VERSION` in the device tree to `4.4`?
> Assuming you have ran `repo_update.sh` and thus have [this](https://android-review.googlesource.com/c/platform/hardware/qcom/media/+/813054) patch, that seems most likely since the code in the error messages show the `4.9` parts from the preprocessor guards.

Thank you @MarijnS95 for your reply!
To address your question regarding the change, I did edit file _device/sony/tone/_**PlatformConfig.mk** (the edited line goes `KERNEL_PATH := kernel/sony/msm-4.9`). Then I ran ./repo_update.sh and started building (which in turn resulted in the above mentioned errors).
Regarding the patches, it seems they concern **msm8998** board in most parts, so that **msm8996** board doesn't get those updates and hence runs into build issues. I think I need to incorporate the patches in a similar fashion as _msm8998_ for _msm8996_. But I may be wrong since this development and contribution is fresh to me.
Please, correct me if I'm wrong.

**Comment by MarijnS95** [comment]
@b1mt3 Yes, changing `KERNEL_PATH` is one of the changes necessary, but you'll also need to change the aforementioned `TARGET_KERNEL_VERSION`.
In fact, I have a patch in my local repository that uses `KERNEL_PATH := kernel/sony/msm-$(TARGET_KERNEL_VERSION)` (which I'll PR to the main repo ASAP).

Regarding the msm8996 driver, all platforms are using the 8998 driver currently. As far as I know because it is the most maintained and simply compatible with all of the boards (in other words, I don't understand why there are so many separate drivers/HAL's when they are basically duplicates of each other).
In any case, if you look closely at the logs you'll see that it's in fact compiling the `msm8998` media HAL, as it's supposed to. Change `TARGET_KERNEL_VERSION` to `4.4` and it should build fine. If it doesn't you might want a clean-ish build by running `m installclean` and deleting the `out/target/product/dora/obj/KERNEL_OBJ` folder.

**Comment by b1mt3** [comment]
> @b1mt3 Yes, changing `KERNEL_PATH` is one of the changes necessary, but you'll also need to change the aforementioned `TARGET_KERNEL_VERSION`.
> In fact, I have a patch in my local repository that uses `KERNEL_PATH := kernel/sony/msm-$(TARGET_KERNEL_VERSION)` (which I'll PR to the main repo ASAP).
> 
> Regarding the msm8996 driver, all platforms are using the 8998 driver currently. As far as I know because it is the most maintained and simply compatible with all of the boards (in other words, I don't understand why there are so many separate drivers/HAL's when they are basically duplicates of each other).
> In any case, if you look closely at the logs you'll see that it's in fact compiling the `msm8998` media HAL, as it's supposed to. Change `TARGET_KERNEL_VERSION` to `4.4` and it should build fine. If it doesn't you might want a clean-ish build by running `m installclean` and deleting the `out/target/product/dora/obj/KERNEL_OBJ` folder.

@MarijnS95 I see,
Regarding the change of `TARGET_KERNEL_VERSION` to 4.4: does it mean that kernel 4.9 is unbuildable at present? It's just that I'd like to give it a go with kernel 4.9 specifically (call it my "idee fixe").
Regarding the clean-ish build: I personally usually run `make -j N clean`, is it fine? Otherwise, could you re-iterate the command you use, is it really `m installclean`?

**Comment by b1mt3** [comment]
@MarijnS95 thank you for the valuable insights,
for the time being the issue is closed,
I shall follow the recommendations given and build anew.

**Comment by b1mt3** [comment]
@MarijnS95, hello,
sorry for disturbing you,
could you take a look at the build log snippet [here](https://imgur.com/a/aQs7vgz) and maybe help me out with the resolution?
A bit of digging into the matter brought me to OmniROM Gerrit [here](https://gerrit.omnirom.org/#/c/android_device_sony_tone-common/+/22831/) and the file missing (**linux/msm_audio_calibration.h**) in the source tree is present in the commit there, FYI.

**Comment by oshmoun** [comment]
I'm guessing you're missing a patch in audio hal to include the required headers
https://github.com/SonyAosp/platform_hardware_qcom_audio/commit/54f36436dfb24be80d41a55b7f992962472f11bc

**Comment by jerpelea** [comment]
this is not a supported combination !

**Comment by b1mt3** [comment]
@jerpelea 
I spotted a software binary available for tone platform  (Oreo 8.1 / kernel 4.9), so I thought I'd give it a try. But I assume you refer to tone/dora with Oreo 8.1 and kernel 4.9 as a "not supported combination": perhaps the supported ones would be tone/kagura and tone/keyaki.
Anyway, thank you @oshmoun and @MarijnS95 for the insights and help!

**Comment by jerpelea** [comment]
the 8.1 / 4.9 devices are tama devices
