### ISSUE TITLE
Documentation is broken.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#308]
https://developer.sony.com/develop/open-devices/get-started/unlock-bootloader/how-to-unlock-bootloader/

>  On your device, turn on USB debugging by going to Settings > Developer options and click to enable USB debugging. 

Should be OEM unlocking.

> fastboot -i 0x0fce oem unlock 0xinsert your unlock code

Should be fastboot oem unlock 0xinsert your unlock code

> Platform tools 26.0.2 or older are required.

Really? I can't find a link for 26.0.2 anywhere on developer.android.com. I think you mean `or newer`.

**Comment by MarijnS95** [comment]
From `fastboot -h`:

>  -i <vendor id>                           Specify a custom USB vendor id.

This is not mandatory since there's probably only one phone in fastboot mode inserted at a time anyway, but at least an extra safety precaution. For example to make sure your device is at least properly detected as a Sony device (because `0x0fce` is their vendor id).
While it will work fine without it, it's strange your phone wasn't picked up like that (but definitely *not* broken documentation).

**Comment by jamuir** [comment]
Newer versions of fastboot do not accept the "-i" parameter.

The docs should be updated.

**Comment by MarijnS95** [comment]
https://android.googlesource.com/platform/system/core/+/f3192bd05231eb6d1c9307885c5400494e38527f

@jamuir Yes you are right, forget I said anything.
That said, it is still on `android-9.0.0_r30`.

**Comment by jamuir** [comment]
@gerg5c42g542g2c54g52c :  rather than edit your original post with new information / questions, could you instead add a new comment?  That helps keep the conversation more understandable.

**Comment by gerg5c42g542g2c54g52c** [comment]
Okay @jamuir . I just remembered about one inaccuracy, so I added it.

**Comment by jerpelea** [comment]
@gerg5c42g542g2c54g52c the parameter is valid on the _r30 and will be removed from the documentation when it will be removed from a stable release
