### ISSUE TITLE
[Night Light support] Do these Xperias have Hardware Composer HAL 2.0 (HWC 2) implementation that can apply the matrix passed to setColorTransform to perform tinting?

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [sonyxperiadev/bug_tracker#319]
> Night Light requires a Hardware Composer HAL 2.0 (HWC 2) implementation that can apply the matrix passed to setColorTransform to perform tinting without impacting power, performance, and app compatibility.

- https://source.android.com/devices/tech/display/night-light

Which devices currently supported by Sony Open Devices program support this? Does Xperia X support it?

**Comment by MarijnS95** [comment]
On Suzu (probly the entire Loire platform):
The underlying display driver/library reports to HWC2 that it supports it, but errors out when using it.
We've added a property to use the GPU fallback path in https://github.com/sonyxperiadev/bug_tracker/issues/80. 
I don't know where the problem lies; it could be lacking hardware support, or the blobs/kernel are  messed up.

A similar problem occurs on Discovery (Nile platform) with SDE; something returns an error on the closed-source blob side. Even with extremely verbose debug logging, no obvious errors are seen in the kernel.
(That said, I can't remember if nightlight was working there before. But I can definitely tell the hardware responsible for this transform functions just fine, as tested for https://github.com/sonyxperiadev/kernel/pull/1892).

It works just fine on Tama. I don't know about Yoshino or Tone.

**Comment by jerpelea** [comment]
tone, yoshino and tama are working fine

**Comment by gerg5c42g542g2c54g52c** [comment]
@MarijnS95 So Night Light is working fine on suzu, it's just that it uses GPU instead?

Is it enough to set `<bool name="config_setColorTransformAccelerated">true</bool>` in `frameworks/base/core/res/res/values/config.xml` to enable it on this platform? It's referenced by `<bool name="config_nightDisplayAvailable">@bool/config_setColorTransformAccelerated</bool>` in the same file.

**Comment by MarijnS95** [comment]
@gerg5c42g542g2c54g52c So if I understand correctly, all you wanted to ask is whether Night Light is supported on Xperia devices, because the option is not available in the menu?
I've been using Omnirom, and just now see that they have `config_nightDisplayAvailable` enabled in a global overlay - it is not configured in any of the `device-sony-` repos.

If so, I'll PR a change to enable it on all platforms. `config_setColorTransformAccelerated` doesn't seem to be used anywhere else yet, so we can just leave that out until it is used and we are sure which platforms properly support HW accelerated color transforms.

**Comment by gerg5c42g542g2c54g52c** [comment]
@MarijnS95 Yes. I don't really care about the performance hit. source.android.com lists this feature as required (not merely recommended) for Night Light to function, that's why I asked.

I'm up for it. I think this feature should be enabled by default.

**Comment by MarijnS95** [comment]
@gerg5c42g542g2c54g52c See the referenced PR.
