### ISSUE TITLE
[loire/all?] NFC can't send data

### ISSUE THREAD

**Issue by RobbieBnt** [sonyxperiadev/bug_tracker#324]
**Platform:** loire
**Device:** suzu 
**Kernel:** 4.9
**Binaries:** v5
**Android version:** 9.0

**Issue:** 
That's an old and often discussed theme, I'm surprised nobody hasn't reported it.

So, basically the problem is that NFC can receive and read data, but can't send it back. This is important as most of the bank apps and NFC payment methods relies on it.

**Symptoms:** 
Receive: 1
Send: 0

**How to reproduce:** 
Try to use anything that relies on NFC sending.

**Comment by oshmoun** [comment]
tried by sharing a chrome tab between phones, with one of them being loire
the share worked in both directions
would not rule out an issue though, especially when it comes to banking apps, which could be caused by the additional security.
do you have a specific scenario to try? one that fails on your loire device?

**Comment by jerpelea** [comment]
@RobbieBnt  please specify howto reproduce the bug

**Comment by RobbieBnt** [comment]
@oshmoun @jerpelea try using Google Pay. For me it wasn't working even though my ROM was "fixed" in terms of security.

**Comment by jerpelea** [comment]
We do not support Google apps or Google Pay!

**Comment by jerpelea** [comment]
NFC send and Receive works as intended
