### ISSUE TITLE
[Poplar] android-9.0.0_r31 - Speaker randomly dies

### ISSUE THREAD

**Issue by waltercool** [sonyxperiadev/bug_tracker#329]
**Platform:** 
Yoshino
**Device:** 
Poplar
**Kernel version:** 
4.9.152
**Android version:** 
9.0.0_r31
**Description**
After using the device a couple of hours, speakers stop working, no sound happens. No even in calls, notifications or nothing.

Current workaround is powering off the device.

**Symptoms**
- Speaker stop working.
- Headphones works fine.

**How to reproduce**
No idea how to reproduce it

Just attached a file at settings playing with the audio volumes.
[volume-playing.txt](https://github.com/sonyxperiadev/bug_tracker/files/2841566/volume-playing.txt)

**Comment by stefanhh0** [comment]
Sounds like it could have been fixed with:
https://github.com/sonyxperiadev/kernel/pull/1909

**Comment by waltercool** [comment]
Great! Let me pull+recompile and confirm if this is solved

**Comment by waltercool** [comment]
OK, recompiled everything (repo sync + repo_update) under 9.0.0_r31 and happened again.

Should I do some clean before?

**Comment by stefanhh0** [comment]
I always do a make clean before. Which firmware version-baseband are you on?
`fastboot getvar version-baseband` should show: `47.2.A.2.33`  
if you are on an older version-baseband you should update it using:
https://developer.sony.com/develop/open-devices/get-started/flash-tool/

**Comment by waltercool** [comment]
I'm currently using 1307-6628_47.1.A.2.324, how do I update that? I do need to run Emma for it? I mean, because I do only have Linux on my machine.

**Comment by stefanhh0** [comment]
As I understand it, flashing the Sony SW is only possible using Emma. At least I don't know and haven't heard of other methods to do it. It would be great though to be able to just do it from linux. I just tried Emma on wine but it refuses to start because of wrong windows version, although I've set to Windows 10. Winehq.org does not even list emma in their database.

**Comment by stefanhh0** [comment]
Here some findings that should be dealt with care and has the potential to break things utterly and corrupts your host and / or phone with malicious software, maybe even brick your phone:

http://www.flashtool.net/
That claims to run on linux just fine.You can then download the firmware via XperiFirm tool, which is shipped alongside with the flashtool. You have to create a ftf package then and have to create the correct fsc-file (flash-script).  You could also download a prepackaged ftf file from here: https://androidfilehost.com/?w=files&flid=214717&sort_by=date&sort_dir=DESC

I've tried myself on windows and my XZ1Compact (I don't own a XZ1). I just downloaded a file XPERIASITE.PL_XZ1_Compact_G8441_9.0_47.2.A.6.30_PLUSPL.ftf I flashed it and at first it seemed okay, bootet to system just fine and fastboot showed: 47.2.A.6.30. However when I flashed aosp, it no longer booted and I had to revert to the official firmware 47.2.A.2.33 via Emma. I can't say if that was a problem due to  the ftf I've flashed or if the 47.2.A.6.30 firmware is currently not working together with aosp and xz1c. 

Also prepackaged 47.2.A.2.33 ftf files are available for your phone. But I don't know if that is too risky for you, especially since you can't revert using Emms and there is clearly the risk of bricking your phone completely.

**Comment by waltercool** [comment]
Hi,

I finally used Emma under QEMU, getvar version-baseband never changed until I used the "with erase" option, the non-erasing version didn't made anything. Using flashtool also never made baseband to change, tried many ROM versions from XperiFirm (with Mono)

Now, I'm currently testing the speaker, and seems to be working correctly, but it looks like SIM is now broken.

Let me fetch more data about the SIM bug and report into a different issue ticket. For the speaker, let me do more testing before closing this issue as solved.

Many thanks for your help!

**Comment by stefanhh0** [comment]
De nada. I can confirm your observations. The firmware is only applied when the full sony image has been flashed and the phone has booted to the system with an inserted sim card (https://github.com/sonyxperiadev/bug_tracker/issues/270#issuecomment-461110712).

**Comment by jamuir** [comment]
I think the firmware is updated -- it is just that the meta data read by
"fastboot getvar all" is not updated by Emma when you do a firmware
update.  I think the meta data is read from the TA partition, which is not
altered.  Hopefully someone from Sony called confirm or correct me here.

**Comment by jerpelea** [comment]
@jamuir this is correct

**Comment by gerg5c42g542g2c54g52c** [comment]
Confirming this bug on suzu, clean android 9.0.0_r31 built on feb 16. Latest vendor and firmware flashed to device.

**Comment by invalidsudo** [comment]
On my XZ1 Compact with vendor 6, speakers just do not work at all. Bluetooth headphones work.

**Comment by stefanhh0** [comment]
Having the same phone and same behavior... I'll just open another bug.

**Comment by waltercool** [comment]
Just updating.

Using the last version still triggering the issue, using `make clobber` before building and 47.1.A, randomly audio still goes out.

I haven't able to find the reason through, but works correctly using 8.x version (just like WiFi, which I have random disconnections at 9.x).

**Comment by jerpelea** [comment]
@waltercool 
v8 is released !
please rebuild and test

**Comment by gerg5c42g542g2c54g52c** [comment]
Can anybody else confirm this is fixed now? @waltercool @stefanhh0

**Comment by waltercool** [comment]
Oh, just forgot it. Let me recompile today and give you an answer this week (based at experience using the device)

**Comment by stefanhh0** [comment]
@gerg5c42g542g2c54g52c I can't check it since I just own a Lilac not a Poplar and since I never ran into that problem.

**Comment by waltercool** [comment]
OK, after couple of weeks, I can confirm this is solved. Haven't heavily tested Poplar, but all my uses haven't experienced any problem with audio as before. I would say this can be happily close.

Many thanks!
