### ISSUE TITLE
Glove Mode

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#367]
Platform:Any 
Device: Any 
Kernel version: Any 
Android version: Any

Description
Gui switch in setting for glove mode is missing. But touchscreen driver supports it. 
I can enable glove mode using terminal. 
Toggling /sys/devices/virtual/input/clearpad/glove (I'm not sure if path is correct, but it would be something similar) between 1/0 for glove mode toggling. 
Tested on kagura, and it was working. 
So u can just make Gui toggle switch in settings to support it. 
I will test it also on Akari later.

**Comment by jerpelea** [comment]
the glove mode is not an implemented feature

**Comment by kholk** [comment]
We had a discussion about this specific topic quite a lot of time ago, and I think even more than one, so since you're basically asking about it, that's what we've concluded:

Implementing the switch in Extended Settings is really really easy. That takes 60 seconds to do, not an issue. 
Big problem around: glove mode will raise the sensitivity of the touchscreen by "a whole lot" (scientific measurement FTW) and may (and will) produce ghost touch issues in some conditions, so if the user forgets about having it enabled its gonna be a huge issue. 
To circumvent this, stock ROMs are implementing an animation that shows every "tap" that is coming from "glove recognition" so that, in the event that some issue appears, the user is made aware of what's happening and will be promptly able to remind that the functionality is enabled and will go to disable it. 

That second part is what's not easy to do, not without doing a mess in the AOSP code... And that's the reason why we decided to (at least currently) not support this feature on Open Devices builds.

**Comment by Gouster4** [comment]
Implementing the switch in Extended Settings is good enought solution. And if it will also enable "show taps" from dev settings, it would be even better. Sure it should be disabled by default, but there would be still option for users to enable it.

**Comment by kholk** [comment]
Your suggestion is sort of dubious, but we can sort that out by showing an
informative window to the user warning him that the Glove Mode functionality
does use that Android option to signal that it is currently enabled.

This means that your suggestion is currently under review and we are
probably accepting it as a solution for the raised issue.

@MarijnS95 is looking forward to implement the functionality.

**Comment by MarijnS95** [comment]
@Gouster4 You can try out a "preview" here: https://github.com/MarijnS95/packages_apps_ExtendedSettings/tree/glove_mode

It's still a little bare-bones, missing translations and the mentioned tap circle; the latter one which is easy to add later.
I'm currently doubting whether to apply some refactors to ES. While I don't want to be "that guy", the one who changes all the code to his own liking, there's certainly improvements to be made. Especially with regards to reducing similar/duplicate codepaths and reusing these for the different (sysfs) preferences. Of which I've introduced another load of duplicate bloat with the glove mode.
