### ISSUE TITLE
[TONE][DORA] No deep sleep at all

### ISSUE THREAD

**Issue by mydevilroot** [sonyxperiadev/bug_tracker#392]
**Platform:** Tone
**Device:** Dora
**Kernel version:** 4.9 
**Android version:** 9.0

**Description**
The phone battery is draining too fast, **there is also no deep sleep at all.**
I've tested in many scenarios, every single time the results was the same:

1. With sim inserted
2. Without sim inserted
3. With gapps
4. Without gapps

"CPU SPY Reloaded" shows Wake Locks caused by "Android System".

**Symptoms**
Phone battery is draining 10% hour while not used, drains about 20%+ while just launching preloaded apps.

**How to reproduce**
Built latest rom for dora (number 26) flash it with latest oem, install some software like "AccuBattery" to see draining in %

**Comment by ix5** [comment]
Tagging @kholk again because you replied in the wrong bug thread.
This one's the sleep bug :)

And yes, the wakeup bug should be fixed.
@mydevilroot please use an app that traces wakeup sources more accurately than "Android System". Our kernel reports the exact source of wakeups since https://github.com/sonyxperiadev/kernel/pull/1891, and apps such as [BBS](https://forum.xda-developers.com/showthread.php?t=1179809) can process that.
(An example event would be `epoll_system_server_file:[timerfd7_system_server]`)

You can read up a bit about the things we tried when debugging the issues at https://sx.ix5.org/info/post/debugging-suspend-ideas/ and https://sx.ix5.org/info/post/android-kernel-suspend-debugging-and-tracing/

**Comment by jerpelea** [comment]
it is related to the adsp service not properly started

**Comment by mydevilroot** [comment]
> 
> 
> it is related to the adsp service not properly started

Thanks a lot for fixing the issue, deep sleep seems to working fully properly now, I've made a build today.
