### ISSUE TITLE
[TAMA] VoLTE & call over WIFI support missing

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#401]
**Platform:** TAMA
**Device:** akari, apollo, akatsuki
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
VoLTE & call over WIFI support is missing.
The stock firmware has them.

If these features won't get added, please explain why. :)

**Comment by jerpelea** [comment]
some functions will not work with the current code or they will require blobs and will be implemented later when they can be implemented in a clean way

**Comment by mmarmm** [comment]
Hi @jerpelea , it seems you've confirmed these two features are non functional. I'm used to bugs remaining open until things are fixed. Could you please add references to the other bugs that are open that track these deficiencies? Otherwise, it would be great to keep this one open until these problems are fixed. Thank you.

**Comment by jerpelea** [comment]
this is not a bug and there is no ETA. We will announce when the feature will be available.
