### ISSUE TITLE
[Yoshino][Lilac] AOSP Camera app cant take pictures 

### ISSUE THREAD

**Issue by wyzco** [sonyxperiadev/bug_tracker#412]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.177-g69cc32601555- 
**Android version:** android-9.0.0_r37
**OEM Image:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.img
**Build:** aosp_g8441-userdebug 9 PQ3A.190505.002 eng.wyzco.20190524.095220
**Version baseband:** 8998-8998.gen.prodQ-00197-00

**Description**
AOSP Camera can only take a picture with the main camera on in the 1st instance of running the app after a power-on. It will not take pictures with main camera, after that until its rebooted. The main  camera shows a green tint in the viewer every time its opened after the 1st instance. Whenever i try to take a picture the camera button greys out as if it was already selected therefore no picture can be taken.

**Symptoms**
Taking pictures with AOSP Camera using main camera is not possible.
This problem aslo extends to Open Camera and any other installed camera. 

**How to reproduce**
Did a clean install of everything, installed Gapps.
Open AOSP camera and try to take a picture with the main camera, the first instance will run fine. pics will be taken but upon closing and reopening the main camera will not take any picture and will show a green tint.

**_Here is a log of the activities_**
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3224989/logcat.log)
Dmesg log
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3224990/dmesg.log)

**_Screenshots of the issues_**
![Green tint](https://user-images.githubusercontent.com/4004232/58427916-f95eac80-806e-11e9-9fa4-233bc4fd3530.png)
![Fail to capture(grey button)](https://user-images.githubusercontent.com/4004232/58427917-f95eac80-806e-11e9-9293-487105a86175.png)
![Failed to open](https://user-images.githubusercontent.com/4004232/58427918-f95eac80-806e-11e9-8b7d-39a2eca0f6ad.png)

**Comment by MartinX3** [comment]
Please retry with the v9 OEM image.

**Comment by wyzco** [comment]
> Please retry with the v9 OEM image.

Did, got the same results. I will post the logs later.

**Comment by ix5** [comment]
The green-ish hue and connection error happen on kagura from time to time as well. Might be kernel-related.

**Comment by wyzco** [comment]
> The green-ish hue and connection error happen on kagura from time to time as well. Might be kernel-related.

It is all the time on Yoshino.

**Comment by jerpelea** [comment]
I am using lilac as my daily device and I can not replicate the issue 
Please flash a full 47.1.A.16.20 SW using flashtool (this will wipe your userdata) to have the same base as I have 
if the issue persists we need dmesg and logcat from boot until the camera issue appears

**Comment by wyzco** [comment]
> I am using lilac as my daily device and I can not replicate the issue
> Please flash a full 47.1.A.16.20 SW using flashtool (this will wipe your userdata) to have the same base as I have
> if the issue persists we need dmesg and logcat from boot until the camera issue appears

I flash using Emma and userdata was erased then I flashed the aosp files. And this is what occurs the dmes and logcat attached are from a freshly done install.

**Comment by stefanhh0** [comment]
> **Version baseband:** 8998-8998.gen.prodQ-00197-00

That is a really strange version-baseband string, I've never seen such a version-baseband before. What is the name of the image you have flashed from emma?

- Anyway, flash the full SW image from emma named `G8441_Customized_US 1310-4371_47.1.A.16.20_R8B`, flash the full image not just the firmware.
- After flashing, boot the phone with SIM-Card inserted
- After having booted into the SW/Stock with inserted sim, reboot into fastboot
- `fastboot getvar version-baseband`has to show 1308-8921_47.1.A.16.20 afterwards
- After having verified it, flash all the aosp images

**Comment by stefanhh0** [comment]
Ah, okay now i know, you are showing the getprop: [gsm.version.baseband]: [8998-8998.gen.prodQ-00197-00] that explains it...

**Comment by stefanhh0** [comment]
@wyzco please verify that you are on the expected version-baseband with `fastboot getvar version-baseband` that you are on the correct version-baseband. I am using currently 1308-8921_47.1.A.16.20 and I don't have any problems with the builtin AOSP camera app (though there are known issues with other camera apps on lilac). 

Although we are on different kernel versions (69cc32601555 <> 9ab03839fa99) that should not be an issue, since I think nothing camera relevant was integrated after the commit you are using.  

If the camera app that is shipped with AOSP still fails for you, connect to the phone via `adb shell` reproduce the failure and immediately after having reproduced the issue call `dmesg >/sdcard/dmesg.log` also take the the full logcat output immediately, that is done via `logcat -d > /sdcard/logcat.log`. Upload the two files with your findings to this ticket as they are.

**Comment by wyzco** [comment]
> @wyzco please verify that you are on the expected version-baseband with `fastboot getvar version-baseband` that you are on the correct version-baseband. I am using currently 1308-8921_47.1.A.16.20 and I don't have any problems with the builtin AOSP camera app (though there are known issues with other camera apps on lilac).
> 
> Although we are on different kernel versions (69cc32601555 <> 9ab03839fa99) that should not be an issue, since I think nothing camera relevant was integrated after the commit you are using.
> 
> If the camera app that is shipped with AOSP still fails for you, connect to the phone via `adb shell` reproduce the failure and immediately after having reproduced the issue call `dmesg >/sdcard/dmesg.log` also take the the full logcat output immediately, that is done via `logcat -d > /sdcard/logcat.log`. Upload the two files with your findings to this ticket as they are.


checked the baseband, it shows
`version-baseband: 1308-8921_47.1.A.16.20`

**_Logs taken immediately after the error/issue_**
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3226695/logcat.log)
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3226696/dmesg.log)

**Comment by stefanhh0** [comment]
Okay, yes the logcat contains messages that I don't get when I use the aosp camera. 

Another thing that is interesting, the formatting of your logfiles is different then I am used to. Do you how that comes? The unusual formatting is for both files dmesg.log and logcat.log.

The dmesg seems to be kind of truncated since it ends with `[0m` 

That looks all a little fishy to me. Is that after you have installed aosp without any modifications (no restore of your userdata backup and no other modifications and no other apps installed)? Is the problem still reproducible when you flash all the aosp img's inclusively oem and userdata and then try using the aosp camera without any other changes? How is the logging then? Is it showing the same formatting? Would be cool if you could double-check it that way to verify if the problem then still persists.

**Comment by stefanhh0** [comment]
Maybe it is the terminal that you are using from your linux host, can you tell me which terminal program are you using to execute adb shell? Also, after you have executed adb shell what is the output of the command `env`?

**Comment by wyzco** [comment]
@stefanhh0 I use adb from in windows to take logs. I'm running pure aosp no gapps, nothing really installed only telegram and chromium. The test was immediately after installing aisp files. So it's basically a bare aosp.

**Comment by androlool** [comment]
Compile the kernel yourself. I had the same issue woth the precompiled sony kernel for poplar(xz1)

**Comment by stefanhh0** [comment]
> Compile the kernel yourself. I had the same issue woth the precompiled sony kernel for poplar(xz1)

Interesting, I wasn't thinking it could have something to do directly with that kernel version because the commits after sonyxperiadev/kernel@69cc32601555 looked to me as not to be relevant for the camera - but then I was obviously wrong, thanks for your hint!

> @stefanhh0 I use adb from in windows to take logs.

Okay, Billy Boys glorious good old cmd.exe ;-) I could reproduce the output with it. Means as well my assumption that the dmesg is kind of truncated was wrong it is just control codes for the colors that cmd.exe does not handle appropriately. 
Would be good if you could use a terminal program that does not have such problems, e.g. cygwin bash or some other program that outputs the logs just normally. Or you just use adb from your linux box. With an up-to-date version of windows 10 cmd.exe seems to be more linux compatible in that aspect, however cmd.exe in windows 10 can be switched to legacy mode, with the legacy mode I was basically able to reproduce the log format behavior when getting the dmesg output.

**Comment by stefanhh0** [comment]
I have double checked, remade the bootimage using the precompiled kernel
```
lilac:/ $ cat /proc/version                                                                                                                                                       
Linux version 4.9.177-g69cc32601555-dirty (root@seldlx21330) (Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)) #1 SMP PREEMPT Thu May 23 09:36:11 CEST 2019
```

The AOSP camera just works for me, so that seems not to be the cause for the problem. I haven't checked it though on a bare AOSP but kept my userdata, magisk, gapps-pico,  and other apps. 

Anyway, you could just give it a try and build your own kernel via removing the precompiled kernel `rm -r kernel/sony/kernel/sony/msm-4.9/common-kernel` and rebuilding the bootimage via `make -j 4 bootimage`. 
Who knows maybe that will change something... but I am not too optimistic that it will solve the problem.

**Comment by stefanhh0** [comment]
Another thing, your build is from 20190524.095220 mine is a little older (but only a few hours!), maybe I have overseen something. I will just do a clean build and then I will check if I can reproduce it with a current build.

**Comment by wyzco** [comment]
I have compiles a new build.
```
Kernel version
4.9.177-g9ab038839fa99-dirty
#1 Wed May 29 17:37:39 EST 2019
```
AOSP Camera seems to be working well now :-)

TWRP, GApps-Pico and Magisk installed

**Comment by stefanhh0** [comment]
Very good to hear that! Then you should close the ticket.
