### ISSUE TITLE
[suzu] AOSP 9.0 fails to boot

### ISSUE THREAD

**Issue by Zyxel84** [sonyxperiadev/bug_tracker#413]
**Platform:** Loire
**Device:** Suzu
**Android version:** android-9.0.0_r37

**Description**
I have successfully build AOSP images for Xperia X (F5121) device. I have unlocked the bootloader and successfully flashed boot.img, system.img, userdata.img.
But I can't flash vendor image to it.

fastboot flash oem SW_binaries_for_Xperia_Android_9.0_2.3.2_v8_loire.img
Sending 'oem' (213892 KB)                          OKAY [  6.845s]
Writing 'oem'                                      FAILED (remote: 'Command not allowed')
fastboot: error: Command failed

Do I need to flash recovery.img from AOSP too? I have installed twrp already.

Anyway, I tried to run device without flashing oem partition but it hangs on Sony logo and does not boot.

**How to reproduce**
Follow build instructions for Android 9.0
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0
Flash boot, system, userdata, oem partitions with fastboot. Try to boot.

**Comment by MartinX3** [comment]
Which fastboot version do you use?

**Comment by jerpelea** [comment]
You fail to flash because the Sony SW is too old.
Please update your device sSWw with our flashtool and boot it with a SIM card.
After this you will be able to flash it with AOSP.

**Comment by Zyxel84** [comment]
Thanks. I have updated firmware with Emma. It downloads ~2.6 Gb but flashes very quickly and says that all was successful. After that I can't boot normal, but was able to flash oem partition with fastboot. My fastboot version is 28.0.3. Then I boot to android but it boots too long and after booting it says that There's an internal problem with your device. Contact your manufacturer for details. I am able to see andriod's desktop and then it reboots. What can I do now?

**Comment by jerpelea** [comment]
After a successful flash with EMMA the device should boot normal to android without the need to flash manually anything. Please be sure that you flashed the Software !
In your case I suspect that you flashed the firmware update instead of the complete SW !
Please flash the device again !

**Comment by Zyxel84** [comment]
Thanks again. Flashed the software update with Emma, then flashed AOSP images (without recovery image) with flashtool. But again after booting it says that There's an internal problem with your device. But now device does not reboot and I can work in AOSP.

**Comment by maluus** [comment]
It's a known problem with v8 binaries. v9 is already out and you can give it a try. I found v9 more stable.

**Comment by Zyxel84** [comment]
> It's a known problem with v8 binaries. v9 is already out and you can give it a try. I found v9 more stable.

Thanks. I flashed v9 oem and that message was gone.

**Comment by jerpelea** [comment]
your image and the vendor image were offsync

**Comment by ix5** [comment]
Seems the issue was resolved?
@jerpelea

**Comment by STPKITT** [comment]
Is there any chance to achive this without a sim-card?

**Comment by STPKITT** [comment]
Crappy GitHub won't let me edit my previous comment.
I was asking the previous question because I also get the error
Writing 'oem' FAILED (remote: 'Command not allowed')
fastboot: error: Command failed
when trying to flash SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_loire.img (that's v9 already!). I already rented a Windows 10 PC to be able to run Sony Emma at all and flashed the "service" that seemed most appropiate to me but I'm not really sure which service I needed to flash since they are named in a non self-explaining way for ordinary end users like myself.
It would be great if anybody here could give me a hint and answer if I really need a sim-card for this whole undertaking.

**Comment by jerpelea** [comment]
please flash the full software with emma (not the firmware upgrade)

**Comment by STPKITT** [comment]
Thanks for the reply!
Emma only offers 5 firmware updates and 5 so called "Software Update Content Erase". So then non of those offered options seem to be what I need. I read in the Emma user guide that full software would be listed in Emma as type "Customize" and distribution "Commercial", but those don't appear in my Emma. So how do I make full software items show up in Emma?

**Comment by jerpelea** [comment]
you should use "Software Update Content Erase" because it replaces the whole software

**Comment by STPKITT** [comment]
Thanks very much for being patient with me! Your hint did the trick! It would be great if those things could be named appropiately or if at least the description field inside Emma would tell the user more precisely what's inside those service downloads.
Btw for anybody wondering I flashed the software flagged for France although I'm in Germany since AFAIK the mobile network frequencies are the same in those countries. I also used a deactived sim-card which I don't even know the pin code for but I don't know if a sim-card it actually needed to have success with this.
After all that flashing AOSP and OEM binaries worked perfectly.

**Comment by MarijnS95** [comment]
@STPKITT Fwiw the suggestion to boot with a SIM inserted is to set up the modem. For Android 10 and above I've built our own solution to configure the modem with the right firmware for the SIM: https://github.com/sonyxperiadev/SonyOpenTelephony/. You shouldn't need it to get an otherwise functional device, but inserting a SIM later on Open Devices doesn't work afaik. (Theoretically, when switching to a different SIM on Open Devices one should flash and boot stock as well)

I don't think anyone backported or is using that repository on Android 9 yet though (nor remember whether the underlying modem-switcher binary is even available there).
