### ISSUE TITLE
Light/Dark mode switcher bug on Sony AOSP rom XZ3

### ISSUE THREAD

**Issue by ozamyatin** [sonyxperiadev/bug_tracker#415]
Platform: Tama
Device: Akatsuki (XZ3 Dual Sim) 9436
Kernel version: 4.9.x
Android version: 9.0.x

Description
When trying to change theme from default light to dark in Sony AOSP Rom settings nothing happens. Theme does not change.

Please note that neither theme changer, nor invert color setting do work. 

Symptoms
No reaction, as if no setting was changed.

How to reproduce
Open settings app, choose display. Scroll down and choose theme settings. Choose dark.

**Comment by MarijnS95** [comment]
A full dark mode was never implemented in android Pie. This is to come in Q, but is unfortunately not even in preview 2.5 yet.

However, dark/night mode should have nuanced changes such as a dark background in the quick settings menu and the default launcher. Apps aware of this setting should be able to change as well, though I can't remember seeing any.
Can you clarify whether this is happening or not? And if not, provide a `logcat`? This doesn't seem possible, or at least not related to Sony AOSP since none of the framework sources are modified. Unless it depends on a sneaky property that's defaulted to false which I doubt (since there's no reason to hide it; or the option should've been hidden from the settings).
