### ISSUE TITLE
[TAMA] [AKARI/MAYBE ALL] Lack of ethernet drivers 

### ISSUE THREAD

**Issue by Jsix5** [sonyxperiadev/bug_tracker#446]
**Platform:** Tama
**Device:** Akari/Maybe all
**Kernel version:** 4.9.x
**Android version:** 9.0.x

**Description**
Lack of ethernet drivers

**Symptoms**
No connection

**How to reproduce**
Use a usb OTG to ethernet adapter/android ethernet adapter to test.

**Comment by MarijnS95** [comment]
USB networking is compiled in, but not all drivers for all the specific chipsets are included. This is most likely done to save space since this feature is not used all that often.

Anyway, the easiest is to figure out which chipset your ethernet adapter has (sticker on the back or the internet), or plug it into a computer and check which driver it's using (`dmesg` should show this, or `readlink /sys/bus/usb/devices/*/driver` for the right bus number).

Only a few types are listed as disabled in the defconfigs:
https://github.com/sonyxperiadev/kernel/blob/25b391adb637660ad53d20214519d35c64217305/arch/arm64/configs/aosp_tama_akari_defconfig#L321-L326

These are not all, you can find them in `out/target/product/akari/obj/KERNEL_OBJ/.config`. An example from Akatsuki:
```
1658:CONFIG_USB_NET_DRIVERS=y
1666:# CONFIG_USB_NET_AX8817X is not set
1667:# CONFIG_USB_NET_AX88179_178A is not set
1668:CONFIG_USB_NET_CDCETHER=y
1669:# CONFIG_USB_NET_CDC_EEM is not set
1670:CONFIG_USB_NET_CDC_NCM=y
1671:# CONFIG_USB_NET_HUAWEI_CDC_NCM is not set
1672:# CONFIG_USB_NET_CDC_MBIM is not set
1673:# CONFIG_USB_NET_DM9601 is not set
1674:# CONFIG_USB_NET_SR9700 is not set
1675:# CONFIG_USB_NET_SR9800 is not set
1676:# CONFIG_USB_NET_SMSC75XX is not set
1677:# CONFIG_USB_NET_SMSC95XX is not set
1678:# CONFIG_USB_NET_GL620A is not set
1679:# CONFIG_USB_NET_NET1080 is not set
1680:# CONFIG_USB_NET_PLUSB is not set
1681:# CONFIG_USB_NET_MCS7830 is not set
1682:# CONFIG_USB_NET_RNDIS_HOST is not set
1683:CONFIG_USB_NET_CDC_SUBSET_ENABLE=y
1684:CONFIG_USB_NET_CDC_SUBSET=y
1691:# CONFIG_USB_NET_ZAURUS is not set
1692:# CONFIG_USB_NET_CX82310_ETH is not set
1693:# CONFIG_USB_NET_KALMIA is not set
1694:# CONFIG_USB_NET_QMI_WWAN is not set
1696:# CONFIG_USB_NET_INT51X1 is not set
1700:# CONFIG_USB_NET_CH9200 is not set
1722:# CONFIG_USB_NET_RNDIS_WLAN is not set
3598:# CONFIG_USB_NET2272 is not set
3599:# CONFIG_USB_NET2280 is not set
```

Adding the one you need to the defconfig (with `=y` at the end) and recompiling+pushing the kernel  _should_ get it working (check `dmesg` to be sure). I don't know if android wants a piece for it in terms of HALs but I guess it works out of the box.

**Comment by kholk** [comment]
Ethernet adapters on mobile devices are really uncommon, probably one person on 300
is using one of the many adapters out there and distributing a very FAT kernel with all
the drivers built-in (because that's not limited to ethernet adapters, there are other USB
devices that have no compiled-in driver in our defconfig) is not fair for the vast majority
of the people using Open Devices.

However, the drivers are present in the kernel, as @MarijnS95 showed to you, so, for your
rather rare usecase, your solution is to modify our base defconfig to your needs.
At least that's what I did, too, since I'm another one using an ethernet adapter (but it's on
a device that has no display and has been repurposed as a server).
