### ISSUE TITLE
[tama][akari] Rare crashes

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#455]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9.182-ge167d1f030f2
**Android version:** 9.0
**Software binaries version:** v9

**Description**
i followed a rare crash bug in akari over the time

**Symptoms**
Sometimes the device is stuck frozen and then crashes with several vibrations
I can still deactivate the screen, but not re-enable it
the kernel bug crash is in cpufreq.c:413

**How to reproduce**
Happens rarely.

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

I'm using Omnirom
The last SODP Omnirom sync was end of june.
(Build Date of my rom is 10. august. 2019)

[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/3583476/console-ramoops-0.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/3583477/dmesg-ramoops-0.txt)
[dmesg-ramoops-1.txt](https://github.com/sonyxperiadev/bug_tracker/files/3583478/dmesg-ramoops-1.txt)

Edit:
23 days later, on a freshly full wiped omnirom the same error happened.
So yeah, it is a rare crash.

**Comment by nos1609** [comment]
Rather a hard way issue or vendor-specific one, having same symptoms on a XZ2C with stock firmware, kinda got used to it...

**Comment by MartinX3** [comment]
@nos1609 Or maybe it is just the same code bug which makes it possible to get fixed.

**Comment by jerpelea** [comment]
@nos1609 can you replicate it on Android 10 ?
I tried to replicate your but and I could not 
Have you found any pattern to reproduce it ?

**Comment by nos1609** [comment]
@jerpelea the only pattern I noticed is that it happens during standby or on the opposite during high load and nearly full ram. By the way with LKT module installed on latest stock (sorry, I know it's not something you support) but haven't had any reboots for 3 days since first test. So I think it is rather a scheduler or something kernel parameters related issues rather than a hardware one. I bet on cpu/gpu core/frequency stack, as ram is managed with zram then cpu is engaged. But it is IMHO, I am not a developer :relaxed:

**Comment by jerpelea** [comment]
thanks for reporting it 
unfortunately without a proper way to replicate it is impossible to fix the issue
