### ISSUE TITLE
[ganges] Any way to get 21:9 camera back ?

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#461]
**Platform:** ganges
**Device:** Mermaid
**Kernel version:** 4.9.185
**Android version:** 9
**Software binaries version:** latest 

**Description**
As ganges devices are 21:9 which is absolutely amazing i must say we had 21:9 mode in stock camera. This is no longer the case in AOSP. I have 120fps video and even taking 4K pictures on AOSP with google camera but i still cant find a way to get 21:9 pictures or video.
Is this app limitation or just camera HAL limitation ?

**How to reproduce**
Launch camera app. There is no 21:9 mode

So is there any way we can get 21:9 pictures and video again  or we are just stuck with 16:9 forever ?

**Comment by oshmoun** [comment]
can you check the output of `dumpsys media.camera`? it should list the supported resolutions there.

**Comment by Haxk20** [comment]
[cameradumpsys.txt](https://github.com/sonyxperiadev/bug_tracker/files/3623311/cameradumpsys.txt)
Well one thing is for sure. There isnt any 21:9 resolutions which would indeed match media_profiles_V1_0.xml in ganges repo. I will add the 21:9 resolution in there. Build and test. If it works i will make a PR.
Do you agree ?

**Comment by Haxk20** [comment]
I wasnt able to build AOSP yet. will try to do so tomorrow

**Comment by Haxk20** [comment]
@oshmoun I just got the time finally to build the change and well it doenst work which was kind of expected from me.
I changed the 1080p profile in media_profiles_V1_0.xml to 2560x1080 instead of 1920x1080 and camera apps still dont show it. I suppose this is again limitation of the framework that is used for this platform ?

**Comment by Haxk20** [comment]
BTW am i just blind or are there 2 back cameras in Android 10 ? 
[dumpsys.txt](https://github.com/sonyxperiadev/bug_tracker/files/3648024/dumpsys.txt)

**Comment by sraase** [comment]
If you want to work on it...

Run "adb shell -n dumpsys media.camera" and check the availableStreamConfigurations and availableStallDurations tags (possibly also availableProcessedSizes because of the REPROCESSING support). Only resolutions listed there are available for camera applications. The profile stuff is not relevant here.

The legacy HAL3 implementation is available in vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3HWI.cpp. Start by exposing your 21:9 resolution first, so that apps can select it. Then, have a test app to use that resolution. Watch the logs like a hawk, enable additional logs as needed. Fix all bugs to make it work. The sensor aspect ratio is not 21:9, so you need to make sure the camera stack selects the correct sensor resolution and crops the streams accordingly.

Make sure that the resolution is only exposed on the correct devices, and that you don't break other devices in the process. Different chipsets have different capabilities.

The final patch should be just a few lines of code (if at all, you might get away with some setprop), but you may sink quite a bit of time in getting it to work and verifying that it doesn't break. Feel free to check using CTS. Good luck.

**Comment by Haxk20** [comment]
@sraase Definetly going to look into that. Thanks for the info. It will be very useful.

**Comment by Haxk20** [comment]
@sraase I have never worked with Camera stuff before so this may sound stupid. I looked all around the files and even searched them with grep but i cant seem to find a place where i should add the resolution as there is no config file with vector or array matrix that i could place it in. I found the function addStreamConfig and everywhere its used it takes gCamCapability argument for the config but from there im stuck. IDK how to add the resolution to gCamCapability at all.

**Comment by sraase** [comment]
That is exactly why I told you about all of this. It is not trivial work and takes a lot of time to dive into. There is no simple "these are the supported resolutions"-table. (There is no such table for the new HAL either, but the relevant code is not public.)

If you are interested, then learn about how the Camera2 API works from the framework side (I have published a test application here, but there are many examples), and take a look into hardware/libhardware/include/hardware/camera3.h on how this translates into HAL API calls (it is a _very_ thin wrapper). Then look back into Camera3HWI.cpp where this interface is implemented.

From what I can see (I am not too familiar with the legacy HAL codebase), the gCamCapabilities contains the sensor driver capabilities. You can't add a new sensor mode.

**Comment by Haxk20** [comment]
Damn. This seems more complicated then it should be really.
Will look into it but IDK if i can manage this. But hey i will try.
Im just wondering where it gets its resolutions it supports now. They
cannot be from thin air.

št 26. 9. 2019 o 10:37 Sebastian Raase <notifications@github.com>
napísal(a):
