### ISSUE TITLE
[Q][ALL] Kernel building broken

### ISSUE THREAD

**Issue by Haxk20** [sonyxperiadev/bug_tracker#466]
**Description**
Q is enforcing a lot more restrictions like PHONE ...
And precompiled kernels were used in 4.9 which made the build fine but since 4.9 got dropped and now in master manifests we are running 4.14 without precompiled versions the build is failing since 4.14 branch isnt compatible with the restrictions yet (@ix5 did an amazing job on 4.9 branch here: [link](https://github.com/ix5/kernel-sony/commit/6302f87e5ce1d9198707c42db9c502e0fe62f74b).
It would be good to port those changes over to 4.14 or ship precompiled kernel.

**How to reproduce**
Build

**Comment by MarijnS95** [comment]
It's no secret that 4.14 (nor Android 10 for that matter) is not even close to being ready for general use yet, evident by the fact that these are [not used by any of the AOSP build guides](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions). In that sense it's perfect that there is no prebuilt available yet, as you won't be able to get a working device out of it _anyway_.

Do explain the reason for adding the `bug` label. This is not something we can or should address IMO. Google puts restrictions on invoking outside tools to make builds more reliable, and these restrictions are only going to get harsher. Instead of working around it we should provide prebuilts (again, as soon as they are ready, not a second earlier) and scripts to easily generate these prebuilts and combine it with a ramdisk into a bootable image. This will not harm those interested in general AOSP building, while at the same time benefiting aspiring kernel developers with a fast path to iterative development (depending on the machine, the AOSP build system can adds tens of seconds of useless compiling/generating time on top).

Despite efforts to make master "compile at all times" like other projects, that has simply become an infeasible job with a small but dedicated open source community working on tens of repositories at the same time, doing the conversion to kernel 4.14 _and_ Android 10 at the same time.

**Comment by Haxk20** [comment]
@MarijnS95 I fully agree that shipping prebuilt and have a script to make bootimage from yourself build kernel is the right move.
The reason to add bug label was TBH none. This isnt a feature request.
Oh and you mentioned that 4.14 woudlnt give you functional device.
Does that mean that 4.14 is non functional for now (Some stuff not working) ?

**Comment by MarijnS95** [comment]
The reason you are not seeing software binaries for 4.14 nor any related branches (`master` and/or `LA.UM.7.1.r1`) used anywhere in the build guide is because development is still in full swing, and all devices are currently lacking some or all of its core functionality (from crashing when the screen turns off to not booting at all). In reality there are a few "desyncs" across the project that are simple to solve, after which we should be able to get it working reasonably well for general development.

Though I strongly recommend _against_ using this kernel on a "daily driver" device for at least another 1-2 months, until all the issues are ironed out and all the remaining features supported. A good indicator is the software binary download which (by the time it shows up) should have an alpha/beta designation, and a small comment field explaining potentially missing features. Of course, looking at active PRs and bugs created by those brave enough to try will give an even better impression.

Before you ask, I may be a bit harsh in my posts for no good reason. After all, there is no overview page (anymore?) explaining the _current and future_ status of this project. What (large) transitions we are working on, which branches to pick in case you feel confident battling a few rough edges along the way, where to help out when contributing, etc.

I will discuss the creation of such an overview page, either on the Sony developer site and/or github, as long as it's up-front and easy to find. At the same time a 4.9 fallback branch for Android 10 might be a necessity.

**Comment by Haxk20** [comment]
@MarijnS95 Indeed such an site would be awesome.
I fully understand 10 and 4.14 is still in fullswing development but TBH that wont stop me from using it.
If the phone wakes me up, I can connect to internet and i can make a call then the device is kind of usable as daily driver. 
So if you need somebody to test 4.14 on mermaid im full in. if well i can make a call and connect to wifi :)
And 10 runs very well on mermaid. Not counting that alarm bug which was fixed already either way then well its stable with 4.9.
And i believe i can close this "bug".

**Comment by MarijnS95** [comment]
Of course, feel free to use it but do expect issues along the way. Even if the device works fine you'll run into unexpected problems, such as RescueParty giving you a nice reboot-to-recovery when the device is not plugged into USB (now who tests these cases when they're trying to collect logs...), unexpected sleep/resume issues together with battery drain, and anything random really.
Seeing as you are a developer I am silently hoping for not just tests but also some contributions along the way. I do not know about your intentions but we can definitely use more assistance on this massive project with an ever-expanding base of supported phones :wink:

**Comment by Haxk20** [comment]
@MarijnS95 I will try to contribute as much as i can. Dont expect much tho. Im a full time student by day in my last year of high school so free time is sometimes rare.
And i may be a developer im not really good at kernel development :)
This may sound funny as my bio says im C dev but well im really not great at kernel development but i will try to help as much as i can everywhere.

**Comment by Haxk20** [comment]
@MarijnS95 BTW before you said you are sometimes harsh which isnt the case at all. You are a good person to talk to so far when i reported a bug. So no you are not harsh.

**Comment by MarijnS95** [comment]
The same holds true for me, also being a student with day-to-day responsibilities. I can only advise to start as early as possible with kernel development, if you are even remotely thinking about going that direction. I didn't take that chance when I was your age, and am currently desperately trying to catch up as an aspiring kernel developer.
However as you must have undeniably seen there are many other components involved, and development is welcomed _anywhere_, not necessarily just the kernel. Here, again, all I can is encourage to start on something - even when only remotely feeling capable for it (as long as time allows it, of course. Not wanting to pull you from studying in any case). To be fair, contributing to open source projects is what pulled me through a boring and useless computer science track :stuck_out_tongue: 

> BTW before you said you are sometimes harsh which isnt the case at all.

That's good to hear. I'm usually fairly direct when it comes to "educating" people on the status of a project or telling them how to do things (even when there's no way they could have known...), glad it doesn't come across as bad as I thought.

**Comment by Haxk20** [comment]
@MarijnS95 Will do. Thanks.

**Comment by Haxk20** [comment]
@MarijnS95 Also do you have any recommendations on where i should start in kernel development ? Any good documentation ? Or just your tips would be welcome.

**Comment by Haxk20** [comment]
BTW do you have telegram or any type of contact ? It would be good to have some guidence from time to time and not having to write to old bugs and mention you there. Thats just silly.

**Comment by Haxk20** [comment]
@MarijnS95 Do you know what this error is about ?
FAILED: ninja: 'out/target/product/mermaid/obj_arm/HEADER_LIBRARIES/display_intf_headers_gralloc1_intermediates/export_includes', needed by 'out/target/product/mermaid/obj_arm/SHARED_LIBRARIES/libOmxVdec_intermediates/import_includes', missing and no known rule to make it
It seems to be releated to hardware/qcom/media/sm8150.
Do we still need to revert sonyxperiadev/local_manifests@52af0a2 and sonyxperiadev/local_manifests@91c8fe5 ?

**Comment by MartinX3** [comment]
> @MarijnS95 I will try to contribute as much as i can. Dont expect much tho. Im a full time student by day in my last year of high school so free time is sometimes rare.
> And i may be a developer im not really good at kernel development :)
> This may sound funny as my bio says im C dev but well im really not great at kernel development but i will try to help as much as i can everywhere.

> BTW do you have telegram or any type of contact ? It would be good to have some guidence from time to time and not having to write to old bugs and mention you there. Thats just silly.

@Haxk20 
You're not the only full time student, so don't worry.
Everyone finds his task. :)

Nice to see your intention
Communication is mainly made on a slack server.
Please contact alin jerpelea via email, XDA forum (via PM), sony open devices forum (via PM), twitter (via PM)
He just needs your email and your "why I want to join" message
https://developer.sony.com/develop/open-devices/more-information/contribute-and-support

**Comment by Haxk20** [comment]
@MartinX3 Thanks. I will definetly do so tomorrow or the next day.

**Comment by Haxk20** [comment]
@MartinX3 A quick question. I sent him PM 2 days ago but i havent heard from him yet. Im sure he is busy but i mean shooting an invite isnt something that takes too much time. Should i wait or PM him on different platform ? (Original message was sent on XDA)

**Comment by MartinX3** [comment]
@Haxk20 sometimes it takes a bit, he is a very busy person. :)

**Comment by Haxk20** [comment]
Ah i see. Thanks for letting me know.

pi 27. 9. 2019 o 19:11 Martin Dünkelmann <notifications@github.com>
napísal(a):
