### ISSUE TITLE
[Yoshino][Lilac] Android-10 Screen lag when entering SIM PIN 

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#467]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.189-g5701b92270bf
**Android version:** android-10.0.0_r1
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.zip
**Version baseband:** 1308-8921_47.1.A.16.20
**Build:** aosp_g8441-userdebug 10 QP1A.190711.019 eng.stefan.20190923.205535

**Description**
The comment: https://github.com/sonyxperiadev/bug_tracker/issues/456#issuecomment-534253025 and following is about this issue as well.
After the phone booted entering the SIM PIN the screen reacts very slow and lags a lot.
Same happens when removing the SIM card and entering just the device PIN on boot.
Workaround: Switch off the display and reactivate, after that speed is normal. 

**Symptoms**
Screen-lag when trying to enter SIM PIN.

**How to reproduce**
Reproduces always just start the phone and try to enter the SIM PIN or device PIN.

**Additional context**
Logcat and dmesg were taken directly after entering the PIN and then the screen went off after reactivating the screen reaction of the display was just normal.
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3644479/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3644485/logcat.log)

**Comment by MarijnS95** [comment]
`W SurfaceFlinger: Faking VSYNC due to driver stall` shows up in logcat a lot before the screen is blanked. Unfortunately there's nothing related to it in dmesg where I would usually expect to see the same timeouts, making this a potential userspace software issue.
For now let's see if others can reproduce this and provide the same logs. I'll try to do so locally, though again it's curious that this only happens with Lilac (or Yoshino) on Android 10...
Otherwise we might need to add some probes to SurfaceFlinger and HWC2, or wait for 4.14 together with new binaries to show up.

One thing to note is that yoshino still has `CONFIG_REGULATOR_DEBUG=y` polluting dmesg with useless regulator warnings.

**Comment by jerpelea** [comment]
this combination is not supported by our project
