### ISSUE TITLE
[ALL] Android 10 thermal service tombstones found 

### ISSUE THREAD

**Issue by stefanhh0** [sonyxperiadev/bug_tracker#470]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.9.189-g5701b92270bf
**Android version:** android-10.0.0_r1
**Software binaries version:** SW_binaries_for_Xperia_Android_9.0_2.3.2_v9_yoshino.zip
**Version baseband:** 1308-8921_47.1.A.16.20
**Build:** aosp_g8441-userdebug 10 QP1A.190711.019 eng.stefan.20190923.205535

**Description**
On startup of the phone several tombstones are written something is not working/crashing in the `/vendor/bin/hw/android.hardware.thermal@1.0-service` 

**Symptoms**
No symptoms, I have just found the tombstones 

**How to reproduce**
Just start the phone then the tombstones are written.

**Additional context**
[tombstone_22.log](https://github.com/sonyxperiadev/bug_tracker/files/3656163/tombstone_22.log)
[tombstone_23.log](https://github.com/sonyxperiadev/bug_tracker/files/3656164/tombstone_23.log)
[tombstone_24.log](https://github.com/sonyxperiadev/bug_tracker/files/3656165/tombstone_24.log)
[tombstone_25.log](https://github.com/sonyxperiadev/bug_tracker/files/3656166/tombstone_25.log)

**Comment by MarijnS95** [comment]
@stefanhh0 This is caused by a little bug in the default thermal passthrough implementation. The `module` variable [here](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-10.0.0_r2/thermal/1.0/default/Thermal.cpp#183) is not initialized to `NULL`. We do not have a (default) thermal hardware module so this value stays random, in turn crashing as soon as `getTemperatures` tries to dereference that random value.

Nothing we can't fix, but it leads to more questions than answers:
- It has been like this on android 9, where we do not include a thermal module either. Has everyone just ignored this bug there? Was the compiler inserting a zero-initialization? (Perhaps, but that would be weird: `hw_get_module` sets it to `NULL` when not found?)
- Do we fix the issue and send it to gerrit?
- Do we include `thermal.default` (+ sepolicy) now? This is the default hw module implementation that provides all `/sys/class/thermal/thermal_zone*/temp` to the framework.
  This doesn't seem remotely useful since they all result in an unnamed, unknown temperature probes without unit. All files expose the value in integer millicelsius currently. We can silence the error this way, but it will be meaningless.
  In case you want this, cherry-pick:
  - https://github.com/MarijnS95/device-sony-common/commit/0ded380d01478b8560ed8172d9b0a2a62a4cd9c8
  - https://github.com/MarijnS95/device-sony-sepolicy/commit/fe29144d863e1fcb59ef65aa33e84dfa5b30a845

I'll discuss whether we should put some effort in pulling the 2.0 HAL from Pixel devices. This exposes all the new functionality including cooling devices (passive throttling in our case).

Btw, you can edit the title to `[ALL]`, this affects every device.

**Comment by stefanhh0** [comment]
I've cherry-picked the two commits and the tombstones are no longer written.

**Comment by chris42** [comment]
FYI: I am just trying to get these commits. However it seems, that they are not part of a branch, hence cherry-pick gives bad-object.
Also git denies to fetch them:
`error: Server does not allow request for unadvertised object 0ded380d01478b8560ed8172d9b0a2a62a4cd9c8`

**Comment by MarijnS95** [comment]
@chris42 That happened to @stefanhh0 [before too](https://github.com/stefanhh0/aosp-10/commit/d0347c166df6a9920a34d6fefbb1269d7e6a4c71), because I keep force-pushing my branches. That'll give different commits without matching hashes. The old (now unreferenced) ones stick around in Stefan's local repo for a while until `git gc` picks them up.

I can push some stable branches for this, but you might as well not bother and live with the thermal crash.

**Comment by stefanhh0** [comment]
Just updated the commit hashes and pushed them.

**Comment by stefanhh0** [comment]
@MarijnS95 any news on this issue? Not that it is the most serious one currently, but because it came up again see: https://github.com/sonyxperiadev/bug_tracker/issues/587#issuecomment-635064404 I just thought I am going to ask again.

Btw. meanwhile I have cherry-picked the two commits from you and put it to a stable branch sometime ago.

**Comment by MarijnS95** [comment]
@stefanhh0 This issue currently stands exactly at https://github.com/sonyxperiadev/bug_tracker/issues/470#issuecomment-535689477. We did not have time nor the intention to address this issue. As far as I can tell from the HIDL Android can only use this to retrieve thermal information about the system, not act on it to enable cooling devices AFAIK. Perhaps it slows things down in the framework or otherwise uses it for statistics, I have no idea.

Yeah, perhaps we should use the (meaningless) default module and be done with it for now. @ix5 what do you think? We are currently swamped with a ton of other work, including supporting a new platform (and another one a couple months from now) and I don't want to worry about setting this up. Might be an interesting starter issue though.

**Comment by ix5** [comment]
Meh, maybe patching hardware/interfaces to set the default module to NULL or whatever it was can work for now.
This "bug" impedes no functionality

**Comment by MarijnS95** [comment]
Sounds good, I'll prepare a CL tomorrow.

**Comment by ix5** [comment]
https://github.com/sonyxperiadev/repo_update/pull/127
Already done
@stefanhh0 mind testing it for sanity? Don't have any free space for pulling a clean tree atm.

**Comment by MarijnS95** [comment]
While at it, don't forget to remove prior patches. They'll be unnecessary and hide the issue.

**Comment by stefanhh0** [comment]
:+1:  Will test it tomorrow and remove the patches that hides the error, thanks for the quick fix!

**Comment by stefanhh0** [comment]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.182-g0a6ca56daf71¹
**Android version:** android-10.0.0_r36
**Software binaries version:** SW_binaries_for_Xperia_Android_10.0.7.1_r1_v7a_yoshino.img
**Version baseband:** 1307-7511_47.2.A.11.228
**Build:** aosp_g8441-userdebug 10 QQ2A.200501.001.B3 eng.stefan.20200529.182059

**Description**
The bug has been fixed with: 
https://android.googlesource.com/platform/hardware/interfaces/+/3861f7958bec14685cde5b8fee4e590cece76d68

`/data/tombstones` is empty.

**How to reproduce**
Used the script https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh to build the version.

The aforementioned commits:
https://github.com/stefanhh0/device-sony-common/commit/9e84337598ccc8d5af56267d448ac5b30b916e30
https://github.com/stefanhh0/device-sony-sepolicy/commit/cb62eaecd7b561b3bf83c8240f99c1ea21d151a6
are no longer included.

**Additional context**
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/4704027/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/4704028/logcat.log)

---
¹) 0a6ca56daf71 is not a commit that can be found on github it has been created via
cherry-picking https://github.com/sonyxperiadev/kernel/pull/2272 +
cherry-picking the first 54 commits from: https://github.com/sonyxperiadev/kernel/pull/2273 onto:
https://github.com/sonyxperiadev/kernel/commit/1aaf380ed91b99fd8816a6924fc083ccba43d446
