### ISSUE TITLE
[tama][akari][9.0][4.9] FPC sometimes can't wake up display / unlock until restart

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/bug_tracker#478]
**Platform:** tama
**Device:** akari
**Kernel version:** 4.9
**Android version:** 9.0
**Software binaries version:** OEMv9

**Description**
The FPC (Finger Print Controller) doesn't work if you want to unlock the display / wake up the screen.

It still works as example in magisk, but a bit slower.

**Symptoms**
The FPC doesn't work and throws errors.

**How to reproduce**
Happens rarely.

**Additional context**
[dmesg.log](https://github.com/sonyxperiadev/bug_tracker/files/3694378/dmesg.log)
[logcat.log](https://github.com/sonyxperiadev/bug_tracker/files/3694379/logcat.log)

Maybe there is something, maybe not.
I know 4.9/ 9.0 are now in legacy mode, but maybe this issue ticket helps somehow somewhere.

**Comment by MarijnS95** [comment]
@MartinX3 I think _we_ have discussed this quite a few times already?

The cpu throttles down too aggressively, causing it to pretty much freeze up in the TZ when processing a sensor capture. We need something like a powerlock, but have not had the time to implement it in the power HAL.

**Comment by MartinX3** [comment]
I sadly don't remember this few discussions.

Interesting to know.
My phone was at 30-33°C as it happened.
It didn't happen in the summer as I reached 70?°C in the sun and my mobile network did shutdown due to the heat.

**Comment by MarijnS95** [comment]
@MartinX3 I have mistakenly misread your report after only seeing the last part of logcat. It seemed the common case where there is a fingerprint wakeup followed by 25-something seconds of nothing, when the authentication finally continues and succeeds (curiously, there have been no log messages before the next wakeup).

The logs only show authentication cases for magisk, not keyguard which you mentioned does not work at all. Anyway, this seems an issue in the android system or misuse of the FingerprintService by Magisk more than anything else. It is requesting `getAuthenticatorId` quite a few times, before calling `cancel()` a bunch of times on the HAL _without starting an authentication session in the first place_.

Is this on a custom ROM? I'm leaning towards the system/framework being the issue here, which isn't unlikely on ROMs...
When did this start happening? I've been using omnirom until Android 10 came out and never faced this issue, but have been rolling a very different state syncrhonization mechanism for [fingerprint gestures](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50). You might want to check that out (don't forget the PRs to common and sepolicy) but keep in mind I'm doing the rework explained in the PR right now. Might want to wait a little while before that is ready and pushed.

**Comment by MartinX3** [comment]
It happens multiple times because due to a bug in the magisk manager app cancel doesn't remove the FPC dialogue, instead it opens it again (if I want to give an app root with the sliders)
I use magisk 19.4 at the moment.

It happens rarely :)
Like the akari crash I reported somewhere else.

I have time to wait :D

**Comment by MarijnS95** [comment]
So there is a possibility Magisk is misbehaving and pulling down the system service. I do not see any authentication request from keyguard when the screen turns off.

Android _should_ cancel any ongoing authentication request when the screen turns off, so either Magisk is withholding it in some way, or the system itself is borked. Again, this seems like a ROM issue, nothing wrong with the FPC HAL.

**Comment by MartinX3** [comment]
I hope with you.

**Comment by ix5** [comment]
Unless this is still reproducible, this should be closed.
Magisk is unofficial and not part of SODP.

**Comment by MartinX3** [comment]
I switched to 4.14 and will look for this issue.
