### ISSUE TITLE
[Kumano] Android Pie/9

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/bug_tracker#481]
The stock rom for kumano on release is Android Pie/9 based. Is it still possible to run the device using open devices with Android 9?

**Comment by jerpelea** [comment]
NO
AOSP Android 9 does not have the necessary code

**Comment by Thaodan** [comment]
Which code is missing? I mean it runs under Android 9 in stock too?

**Comment by jerpelea** [comment]
You need to backport the SOC support to Android 9

**Comment by Thaodan** [comment]
You mean inside the device repo or you mean if I'd use linux 4.9?

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/repo_update/commit/d19e3cb70ffac5af461d6018e10485f4dba570c8 these?

**Comment by jerpelea** [comment]
I am reffering to the 4.14 kernel and all Android repos that are HW dependent

**Comment by MarijnS95** [comment]
Ah yes, google added sm8150 support to the HALs under android 10 tags. So you will have to test if these tags work with an otherwise android 9 build, or filter out the relevant commits and backport them.

Again, nothing too hard I'd say.

**Comment by Thaodan** [comment]
@MarijnS95 Would you be willing to help on this? I expected that the aosp version would be based on Android 9 stock. Didn't had the overview that those might be added later to aosp.

**Comment by jerpelea** [comment]
Unfortunately it is not that simple

**Comment by MarijnS95** [comment]
@Thaodan not at the moment because I'm fairly time constrained and only have time for small features.

However, I propose the following. Wait for Kumano/Griffin to be properly supported/stable on 4.14, then backport (relevant commits from) device/platform repos. It should be fairly straightforward to get it to build, and all hardware specific repositories are not mandatory to boot _as far as I can tell_. Then we will have to look into compiling android 10 branches or backport commits for things like display and media.

Keep in mind where Alin is coming from though. Over the past few weeks there have been a lot of changes, some of which are Android 10-specific optimizations/simplifications. Anything done to the repositories now is with Android 10 in mind and may not easily be reverted back to Android 9. This also carries over to maintenance after getting the device up; any commits made to sodp and "upstream" aosp HW repos need to be considered and backported, at risk of missing security/safety fixes. After all, "we" - and I speak for myself as hobbyist sodp contributor, but most likely including all the other active contributors - will not really provide support for Pie anymore since there's no real reason not to switch to the latest Android version (which obviously doesn't hold true for Sailfish with a large codebase that can't easily switch to a newer android version, as far as I can tell).

One thing to watch out for is oem blobs. While I do not expect those to be compiled against the newest android 10 hidl interfaces, you never know. Minor version changes are backwards compatible, major versions not.
