### ISSUE TITLE
Compiling of Android 9 for F-8331/Xperia XZ Premium/yoshino fails

### ISSUE THREAD

**Issue by bjoern-vh** [sonyxperiadev/bug_tracker#505]
**Platform:?** 
**Device:Sony XPERIA XZ Premium (F-8831)** 
**Kernel version:** 
**Android version:9.0.0r46** 
**Software binaries version:?** 

**Description**
While trying to compile Android 9 I am getting an error message and the compilation stops immediately. I cannot find anything helpful in internet. I am using a Linux Mint 19.2 64-Bite system and tried the following instructions: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-p-9-0-0-2. Before I had unlocked my bootloader succesfully. 

**Symptoms**
After running the make command I get this message and the process exists:

ninja: error: 'out/soong/.intermediates/vendor/oss/qcrilam/QcRilAm/android_common/proguard_dictionary', needed by 'out/target/common/obj/APPS/QcRilAm_intermediates/proguard_dictionary', missing and no known rule to make it
09:45:14 ninja failed with: exit status 1

**How to reproduce**
Run all 4 steps from the instructions and the source command from step 5. In the instructions is mentioned that I have to choose my device from a list but there is nothing to choose.  Then run make -j4 and the error message will be shown.

**Additional context**
Output at the beginning of make command:

PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_f8331
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.0.0-37-generic-x86_64-Linux-Mint-19.2
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=out

I already tried to append aosp_f8331-userdebug after "lunch" but no difference. Only TARGET_BUILD_VARIANT=userdebug is shown in the above list after starting.

**Comment by MarijnS95** [comment]
Intersting, this issue was just reported by @dlastov in #504...

The fix has already been merged two days ago: https://github.com/sonyxperiadev/QcRilAm/pull/5

**Comment by bjoern-vh** [comment]
Thank you for the fast reply :-)

Unfornutately I don't know what to do. This is all new to me :-(

**Comment by MarijnS95** [comment]
@bjoern-vh `repo sync` again.

But since this is only a single repo, `repo sync vendor/oss/qcrilam` or just `repo sync QcRilAm` should do.

**Comment by bjoern-vh** [comment]
@MarijnS95: Thanks again. I synced it max. 2 hours ago and when I try your commands after a microsecond the output is `Fetching projects: 100% (1/1), done` and that's it. But the question for my model appears after re-run `source build/envsetup.sh && lunch`. After calling make the error message is the same like before... 

BTW: Which is correct: 35 - aosp_f8331-eng or 36 - aosp_f8331-userdebug? I tried both iwth same results...

**Comment by MarijnS95** [comment]
@bjoern-vh This looks to have been one of my bad judgement calls...

I couldn't find any app using proguard rules in a new BluePrint file, and since there was a bugfix for this issue on AOSP that has only been merged to Android 10, the sensical idea seemed to remove proguard optimization since R8 is good enough for that.

And... it works for me... because I locally applied [the fix](https://r.android.com/688498) to `build/soong`. Android 9 pulls in a default proguard configuration, which isn't even completely sane:
```
[ 99% 888/893] //vendor/oss/qcrilam:QcRilAm r8 [common]
Warning in ./build/make/core/proguard_basic_keeps.flags:
  Ignoring option: -dontnote
```

As it turns out, _no android app at all_ in Android 9 has been converted to BluePrint.

For now, the safest you can do is get rid of the mk -> bp conversion entirely:
`git -C vendor/oss/qcrilam checkout 2154fe6`

I will discuss with the other contributors whether we are going to revert this conversion or finally branch off QcRilAm so that our Android 10 developments here are separated from Android 9.

**Comment by kholk** [comment]
QcRilAm is an Android component and it is tied to the Android version.
This means that its repository should be branched to support the new APIs in Android 10, while
kept the same for Android 9 and previous releases.

**Comment by MarijnS95** [comment]
@kholk I can only agree. We spend too much time fixing things for Android 10 _all while keeping it "compatible" with Android 9_, when it has and will always be working fine there.

It is nice to see that new SDKs work on Android 9 and good for sanity... But in the end just a waste of time.

So, with this in mind, I will make sure that any future PRs are only going to be for Android 10. There's far too much to worry about still, and Android 9 compatibility holding us back is simply not an option.

**Comment by kholk** [comment]
No it's not an option. Especially with the API news in Android 10, which will make our life a lot easier in the future, there's no point in keeping backwards compatibility for anything that we have right now.

**Comment by jerpelea** [comment]
I will branh c ASAP

**Comment by MarijnS95** [comment]
And I say that because this is really stupid. The entire SDK thing works _perfectly fine_, it's just me wanting to convert the build script to the newer format which breaks it all. On the one hand one could say such a conversion is useless... But on the other:
- Soong blueprints are parsed much, _much_ faster;
- They are much more readable;
- They are the way forward, with Google slowly phasing out makefiles altogether.

So, even if we have new code that is Android-9 compatible code-wise, I will still go ahead and do the BP conversion on every repo I touch.
