### ISSUE TITLE
Double tap to wake and lift to wake for AOSP

### ISSUE THREAD

**Issue by ApostolosB** [sonyxperiadev/bug_tracker#511]
**Platform:** 
tama
**Device:** 
akari (xz series in general)
**Kernel version:** 
4.9
**Android version:** 
aosp 9
**Software binaries version:** 

**Is your feature request related to a problem? Please describe.**
The stock version of android that came with the phone offered features like double tap to wake and lift to wake that are not present in the aosp version. Those -imo at least- are cool and enhance the user experience. So is it possible to have them in the aosp version or it creates a ton of problems. Thats my question

**Describe the solution you'd like**
Double tap the screen to wake it up, lift the device to wake it up.

**Comment by ix5** [comment]
We had to disable dt2wake for tone on 4.9 due to lost touch issues.
https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/boot/dts/qcom/msm8996-tone-common.dtsi#L283-L307

I don't remember whether the dt2w ever worked on the `clearpad` driver for tama, but you can give it a try here:
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.7.1.r1/arch/arm64/boot/dts/qcom/sdm845-tama-common.dtsi#L442
`wakeup_gesture_supported = <1>;`

You also need to change a config in the overlay and device mk https://github.com/sonyxperiadev/device-sony-kagura/commit/e6bf9d9bf3f6a6149a9e32b91460b400ec6aa853 and then enable the functionality in Settings.

**Comment by rinigus** [comment]
Thank you very much, we will try. Added to my TODO list

**Comment by gferon** [comment]
@ix5 slightly off topic, but I just tried the suggested changes on a build for a Xperia X Compact `kugo` and it works perfectly fine! Thanks :smile:

**Comment by ix5** [comment]
@gferon that's nice to hear, though beware of touch issues after prolonged suspend.
If you are certain the feature works well at least for loire devices, please open a PR to enable dt2w for those devices.

@ApostolosB you might consider applying the needed changes to your tama device, or closing the issue since no one else seems to want to tackle this for now.

**Comment by gferon** [comment]
> @gferon that's nice to hear, though beware of touch issues after prolonged suspend.
> If you are certain the feature works well at least for loire devices, please open a PR to enable dt2w for those devices.

well, there's at least one bug where the touchscreen is inactive on first boot. you have to switch the screen off and on once to make it work. I'll try to get to the bottom of it.

**Comment by rinigus** [comment]
@ix5, I guess closing the issue would be correct as we got the info that was needed. as for testing it on sailfish, let's see when I get to it. right now there are other things in the front of the queue.
