### ISSUE TITLE
[Yoshino] [Lilac] Modem crash

### ISSUE THREAD

**Issue by stblr** [sonyxperiadev/bug_tracker#512]
**Platform:** Yoshino
**Device:** Lilac
**Kernel version:** 4.14.83
**Android version:** 10 r15
**Software binaries version:** v2

**Description**
The device reboots after approximately 1 minute. ~~The screen is on but stays black.~~ No longer the case.

**Additional context**
dmesg: https://gist.github.com/stblr/378bd26d8dacee85e2aeb57a9f3c5044
logcat: https://gist.github.com/stblr/90a58918d698332cfac15986c1090b37

**Comment by andrwgldmn** [comment]
based on your dmesg it`s similar to https://github.com/sonyxperiadev/bug_tracker/issues/425

**Comment by stefanhh0** [comment]
@andrwgldmn thanks for your finding, checked it in the sources and found that the changes are in fact missing for k4.14 so just opened a pull request for it.

However, I can't say if this fixes the actual problem, since the symptoms that are reported by @stblr are different then they have been in #425. Especially the black screen. Could very well be that more work needs to be done for yoshino/lilac.

**Comment by andrwgldmn** [comment]
@stefanhh0 I think we should compare 4.9 and 4.14 to find smth interesting :)

**Comment by stefanhh0** [comment]
I had the same thought like you, that it is not unlikely that more commits are missing in k4.14. But comparing might be a difficult task + I am really just not enough of an expert to do an assessment of the results of such a comparison. If you have any suspicions what might be missing or should be forwarded to k4.14 don't hesitate to open PRs or a bug so that it can be clarified.

Probably best would be to just list the commits that are:
- Not from upstream kernel.org
- Not in k4.14 but are in k4.9 identified by their commit headline

Those would then be the candidates that need to be investigated. However I wouldn't know how to compile such a list at the moment. But would be an interesting task to implement such a script / program that can do something like it. Shouldn't be too difficult with the correct git commands and the right idea.

**Comment by stblr** [comment]
> However, I can't say if this fixes the actual problem, since the symptoms that are reported by @stblr are different then they have been in #425. Especially the black screen. Could very well be that more work needs to be done for yoshino/lilac.

Just to be clear, the black screen issue was probably caused by the wled driver changes and was fixed like 10 days ago. Now it correctly boots to Android but it crashes soon (1 minute or so) after. dmesg and logcat were similar if I recall correctly.

**Comment by andrwgldmn** [comment]
@stblr any progress?

**Comment by stblr** [comment]
Logs with updated sources + sonyxperiadev/kernel#2147:

dmesg: https://gist.github.com/stblr/a3fb9f70ecedd33ab0f3afc424a2fb96

logcat: https://gist.github.com/stblr/5bece6b6a9e9dfb19f7925d4fad003f7

Calibration seems to work but according to dmesg there are still other sde issues.

**Comment by MarijnS95** [comment]
@stblr SDE seems "fine". Indeed, somewhere a UBWC buffer is allocated without an extra metadata layer, but this happens on other devices/platforms as well and we haven't yet figured out what the cause is (blobs most likely) since it proceeds to pass/report valid buffers after that. The other "errors" are most likely all optional features.

What is of genuine concern is the modem subsystem failure:
```
[   59.357602] Fatal error on the modem.
[   59.357729] modem subsystem failure reason: (unknown, smem_get_entry_no_rlock failed).
```
This generally causes a shutdown, perhaps even by the hypervisor.

**Comment by stblr** [comment]
> SDE seems "fine". Indeed, somewhere a UBWC buffer is allocated without an extra metadata layer, but this happens on other devices/platforms as well and we haven't yet figured out what the cause is (blobs most likely) since it proceeds to pass/report valid buffers after that. The other "errors" are most likely all optional features.

Okay, thanks for the info.

> This generally causes a shutdown/crash/reboot, perhaps even by the hypervisor. All the errors following that seem to be in shutdown paths anyway.

Yes the device immediately reboots.

**Comment by andrwgldmn** [comment]
@stblr @MarijnS95 
> ```
> [   59.357602] Fatal error on the modem.
> [   59.357729] modem subsystem failure reason: (unknown, smem_get_entry_no_rlock failed).
> ```


https://github.com/denysvitali/ca-combos-editor/issues/4

**Comment by stblr** [comment]
Modem log: https://gist.github.com/stblr/c62e822c73136bc5136861ac783f1c48

**Comment by wyzco** [comment]
Anyone have a clean build of AOSP 10 I could try with the latest binary to see if there is any change?

**Comment by stblr** [comment]
Logs for latest 10r21 tree and OEM v3:

[dmesg](https://github.com/sonyxperiadev/bug_tracker/files/4082671/dmesg.txt)

[logcat](https://github.com/sonyxperiadev/bug_tracker/files/4082672/logcat.txt)

[modem](https://github.com/sonyxperiadev/bug_tracker/files/4082673/modem.txt)

@wyzco https://drive.google.com/file/d/180woABP6VSGGRUWsr8ZQEMAcgyg2op98/view?usp=sharing
