### ISSUE TITLE
[tama] [apollo] kernel 4.14 bluetooth problem

### ISSUE THREAD

**Issue by nkh990119** [sonyxperiadev/bug_tracker#519]
**Platform:** tama
**Device:** apollo
**Kernel version:** 4.14.83
**Android version:** 10 r21
**Software binaries version:** v3

**Description**
bluetooth connection problem and freeze in listening music

**Symptoms**
Can`t connect with AptX only connect with AAC, play music frequently broken at sleep mode.

**How to reproduce**
connect bluetooth headset and play music in sleep mode

**Comment by nos1609** [comment]
LDAP and AptX are broken with stuttering audion once screen is off, no A2DP offload in Developer Settings

**Comment by MarijnS95** [comment]
LDAC is provided by AOSP and should be available as soon as a compatible pair of headphones is connected. AptX blobs are provided in the odm binaries (afaik also for 4.14, I'll validate that later) and should work as well on compatible headphones.

As for the audio stuttering it indeed seems the SoC is not configured to stay awake properly. Especially with incoming notifications it doesn't increase frequency enough to handle the load.

I run A2DP offloading locally on Akatsuki and notice almost no interruptions whatshowever. This works using both the "old" offloading system from android 9 as well as using the new bluetooth.audio HAL interface. Unfortunately this is based on closed-source libraries coming from crosshatch. Especially the new way of doing offloading requires only a single "dumb" library to forward calls, which is really easy to implement.

However the "closed source offloading system" currently provided in the odm binaries is much more complicated than it should requiring extra serverices and the like, which is why it's not utilized yet. My goal is to reimplement said "dumb library" to have something that's much easier to maintain. Work has not been scheduled yet but it seems about time to expedite it.

**Comment by jerpelea** [comment]
can this bug still be reproduced?

**Comment by jerpelea** [comment]
Android 10 is legacy
