### ISSUE TITLE
[tama] [apollo] kernel 4.14 Night Light crashes after sleep

### ISSUE THREAD

**Issue by nos1609** [sonyxperiadev/bug_tracker#522]
After waking the device the colorization of the screen goes away till the Night Light mode gets reactivated. Issue present on both AOSP with f.lux installed and PixelExperience (built from current Xperia AOSP sources).

**Comment by MarijnS95** [comment]
It doesn't actually crash. It is caused by the fact that we have our own in-kernel color calibration which uses the same hardware (PCC) to apply the color transformations as Night Light.

I have written a kernel hack to intercept the color transform calls from userspace and blend them together with the calibrations that are applied every time the display powers on, which has also been ported to 4.14: https://github.com/sonyxperiadev/kernel/pull/2117/

Unfortunately the change has been reverted temporarily because it breaks the entire display chain on Kumano, and I have so far not had the time to figure out why.

Next time, please DO NOT delete the issue template. It is there for a reason.
