### ISSUE TITLE
Device Cannot Connect to Computers If Flashing from H8296's Stock Firmware First

### ISSUE THREAD

**Issue by samduanx** [sonyxperiadev/bug_tracker#546]
**Platform: tama** 
**Device: akari (H8296)** 
**Kernel version: 4.14** 
**Android version: 10** 
**Software binaries version: 10.0.7.1** 

**Previously working on**
All devices flashed from H8266. (Dual SIM version since H8266 and 96 are dual devices.) Regardless of SODP versions.

**Description**
USB connection with a computer won't work if the device flashed SODP from H8296's stock firmware.

**Symptoms**
Using a Chinese mainland variant (I do not know if that matters) of H8296, when flashing SODP based on any stock firmware of H8296, the USB connection with a computer won't work. Flashing from H8266's will. This also happened in issue #531.

ROM is not compiled by @MartinX3. He claimed that his H8296 worked OOB.

I acknowledge that SODP is designed for H8216 and H8266. I also know that SODP should work OOB on H8296.

**How to reproduce**
1. Flash the stock firmware of H8296 using Flash mode. Boot it up.
2. Flash SODP using fastboot. Boot it up.
3. Connect the phone to a computer.
(The issue could be reproduced with a H8296. I don't have other tama devices.)

**Additional context**
Log gotten with "dmesg | grep -i usb".
[dmesg_log.txt](https://github.com/sonyxperiadev/bug_tracker/files/4241194/dmesg_log.txt)

**Comment by ix5** [comment]
Which stock firmware are you using, respectively?
I see `52.0.A.11.32` as the latest Customized CN for H8296 on XperiFirm, whereas H8266 shows `52.1.A.0.618` for most releases.
Could you see whether the issue lies in the different versions? There should be `.618` available for H8296 via Customized IN.

**Comment by samduanx** [comment]
I have now flashed back to the stock ROM, 52.1.A.0.532 from the HK version.
However, when I was using AOSP I flashed both 52.0.A.11.32 of CN version and .532 from India version, which both did not work. Then I flashed .532 of Customized SG (H8266) which led to a working USB.

**Comment by ix5** [comment]
Ok, thanks for the info.
So that's a tricky one I guess. The main partitions that persist(hah!) from the Stock firmware to installing SODP are: `modem`, `dsp`, `qnovo`, `diag`/`misc`/`appslog`(mostly irrelevant) and... `persist`.
So if you find the time, you could compare the contents of the `persist` partition (mounted at `/mnt/vendor/persist`) between the two ROMs. Qnovo could also be a culprit, but I doubt it. And the bootloader could also be different.

But maybe more straightforward would be capturing logs from working and non-working states.
Please attach the full logs, not filtered with grep. If you think you want to highlight something, you can *additionally* paste excerpts here in triple backticks, like so: ` ``` `

**Comment by samduanx** [comment]
OK, I *may* try to do it again when I have free time since I need my XZ2 in production state for now.

**Comment by ix5** [comment]
Please validate again after https://github.com/sonyxperiadev/kernel/pull/2225

If this is not reproducible, please close.
