### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] Random hard locks while device is idle

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#558]
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.172
**Android version:** android-10.0.0_r30
**Software binaries version:** 10.0.7.1_r1_v4c_ganges

**Previously working on**
Not sure, this is the first time I use an Android 10 / Kernel 4.14 build on this device for any amount of time significant enough to notice this hard lock.

**Description**
Sometimes, apparently in a random manner, after a period of time being idle (in my pocket or on the table) the phone becomes unresponsive to any inputs (power button, fingerprint reader) and the screen stays black.

**Symptoms**
Black screen, no response to input on physical buttons, device is not reachable via USB with adb.

**How to reproduce**
Use the device normally for a few hours / days.

**Additional context**
I activated the Developer option "Store logger data persistently on device: All log buffers" and waited until a hard lock happened. The last lines of the logcat before the lock are attached, but I'm not sure whether they will be useful. There was nothing more in the logcat for around 20 minutes, until I powered off the phone manually pressing Volume up + Power for a few seconds and then booted it again.
[logcat_bugreport.txt](https://github.com/sonyxperiadev/bug_tracker/files/4333178/logcat_bugreport.txt)

**Comment by Haxk20** [comment]
I have seen this issue on Mermaid and well i have suspected it may be releated to calls. And seeing IPA and kernel wake lock there seems to confirm it.
It seems that when device tries to wake up from sleep due to irq signal it goes wrong and basically hard locks. This is untestable for me now. But @xperia10dev if you can please test calls.
Follow these simple steps:
1. Lock device and let it go to sleep (Wait around 20-30 minutes with wifi turned off as to not wake it up by other IRQ signals)
2. Call the device using different device.
One of 3 outcomes will happen.
Either the device wakes up and starts ringing or it will just stay asleep and does not wake up or the worst one that it doesnt wake up and goes into hard lock mode.
If the device wakes up please do the same thing few times as to eliminate any other IRQ signals waking it up. Yes its long process but will help us. Thank you.

**Comment by xperia10dev** [comment]
Tried once, outcome 2 happened: device stayed asleep, did not ring, no trace whatsoever of the call in the call log. Attaching the logcat corresponding to the moment of the call.
[logcat_call_while_device_asleep.txt](https://github.com/sonyxperiadev/bug_tracker/files/4340298/logcat_call_while_device_asleep.txt)

**Comment by Haxk20** [comment]
@xperia10dev Well if you want your device usable i would advise 4.9 kernel. (You will need to clean userdata) cause ganges has this issue. We werent sure if Kirin has it too. Now we are thanks to you.

**Comment by Haxk20** [comment]
@xperia10dev Is there any way you could tell me the exact time you made that call ? Or do it once again and check exact time (Seconds too) when the call was made.

**Comment by xperia10dev** [comment]
Right around this line in the log:
03-16 21:15:15.033  1727  1727 D SST     : NITZ: end=8132277 dur=30

**Comment by Haxk20** [comment]
Very interesting. Thank you. Who knows how long will it take to fix this issue. Most of us are working on something different rn. So as i said. If you want the device as daily driver then run it like me without SIM and use it as normal device and calls on second phone or switch to 4.9 for now.

**Comment by xperia10dev** [comment]
Also got a kernel panic once right after booting which might be related ("Fatal error on the modem"). Attaching contents of pstore after the device panicked and rebooted itself.
[console-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4341577/console-ramoops-0.txt)
[dmesg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4341578/dmesg-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/sonyxperiadev/bug_tracker/files/4341579/pmsg-ramoops-0.txt)

**Comment by xperia10dev** [comment]
Closing this one, as I can no longer reproduce the bug on my kirin device using a clean build with android-10.0.0_r33 branch, prebuilt kernel 4.14.176 and 10.0.7.1_r1_v6_ganges SW binaries. Thanks!
