### ISSUE TITLE
[4.14][10][yoshino][maple]Certain apps will make the device freeze very soon after boot

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#587]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** 10.0.7.1_r1_v7a_yoshino

**Previously working on**
repo_update.sh at around 2020/05/27 PM 3:00

**Description**
Can't really know which app try to call which API then result in freeze and reboot.  
I want to share the system logs but have no idea use what tool.
How can I save the log to PC then can upload to here?

**Symptoms**
An unknown app try to call an API after boot then system freeze and reboot

**How to reproduce**
Nope... I need to share the log to see what software try to do what...

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by mhtvsSFrpHdE** [comment]
Or it's just running too hot? Is a thermal management problem?
This bug didn't show again after the device put there 20 minutes to cool...

I'm going to collect more traits.  I found an old phone can use to call  
so the XZP can run AOSP all day, or say crash all day lol

Anyway the more crash, the more potential problem we find.

**Comment by stefanhh0** [comment]
The thermal might be mitigated with: https://github.com/sonyxperiadev/kernel/commit/67e9edbfaf59513541dd4168f4e0b920acfec3f8 
can you check on what kernel commit you are, using `adb shell uname -a`

Also, there is  general thermal hal bug:
https://github.com/sonyxperiadev/bug_tracker/issues/470

There is a workaround via cherry-picking thermal hal:
https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh

**Comment by stefanhh0** [comment]
Additional, currently there seems to be some stability problems, especially wakeup from sleep for the small Yoshino/Lilac is a problem. Since Maple is as well a yoshino there could be a connection.

See as well the reports I made on: https://github.com/sonyxperiadev/kernel/pull/2268

It would be helpful if you could upload the files that are in `/sys/fs/pstore/` they may contain important diagnostic information.

You can get them via `adb pull /sys/fs/pstore`

Additional boot the system while connected to USB and execute following commands:
`adb logcat >logcat.log`
Press Ctrl+C after you have logged in to your phone and waited lets say ten seconds
Do as well a:
`adb shell dmesg >dmesg.log`

Upload all files, that is: all files from `/sys/fs/pstore`, `dmesg.log` and logcat.log to your initial comment of this issue into section additional context.

**Comment by kholk** [comment]
Please recheck this issue with the following solution: https://github.com/sonyxperiadev/kernel/pull/2309

**Comment by mhtvsSFrpHdE** [comment]
@kholk Okay one of my Xperia XZ Premium were used in work these days  
and can not be erased for new system.

I'll grab another Xperia XZ Premium(I got two) to unlock bootloader soon to do test

**Comment by mhtvsSFrpHdE** [comment]
This issue can cause by many reasons, the closest one is "wake up from sleep then system crash".
If never unplug the phone from power, there's no such problem
