### ISSUE TITLE
[kirin] [aosp 10] [kernel 4.14] Unable to boot

### ISSUE THREAD

**Issue by xperia10dev** [sonyxperiadev/bug_tracker#591]
**Platform:** ganges
**Device:** kirin (i4113)
**Kernel version:** 4.14.176-g6d2c74a49d312 (prebuilt), 4.14.176-g1aaf380ed91b (HEAD)
**Android version:** android-10.0.0_r35
**Software binaries version:** 10.0.7.1_r1_v7a_ganges

**Previously working on**
Kernel version: 4.14.176-g6d2c74a49d312 (prebuilt)
Android version: android-10.0.0_r33
Software binaries version: 10.0.7.1_r1_v6_ganges.img

**Description**
Unable to boot

**Symptoms**
Stuck forever at the animated android logo

**How to reproduce**
Try to boot the device

**Additional context**
[logcat_head_kernel.txt](https://github.com/sonyxperiadev/bug_tracker/files/4705175/logcat_head_kernel.txt)
[logcat_prebuilt_kernel.txt](https://github.com/sonyxperiadev/bug_tracker/files/4705176/logcat_prebuilt_kernel.txt)
logcats attached after boot attempt with both prebuilt and HEAD kernels.

**Comment by MarijnS95** [comment]
@xperia10dev Have you read the logs? Have you figured out the issue in the meanwhile? Apologies if this sounds harsh, but Sony open devices is a project that provides a platform for developers to build their software on top: be it custom roms or anything else. This includes responsibility from the developer/builder themselves to at least attempt to read and understand the logs, usually realizing it's a local issue. We are always willing to help, as long as mutual effort is shown.

That said, allow me to read the logs for you this time. It looks like you did not `make installclean` before building but are instead on a dirty rebuild:

```
05-30 07:30:25.007  7097  7097 E vndksupport: Could not load /vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so from default namespace: dlopen failed: cannot locate symbol "_ZN8loc_core14LocDualContext16mLocationHalNameE" referenced by "/vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so"....
```
We recently migrated to `gnss@2.0`, but the old passthrough implementation for `gnss@1.1` is still on your system.

**Comment by xperia10dev** [comment]
@MarijnS95 no apologies needed, I may have indeed misunderstood the project's goals and tried to use the builds as an end user more than as a developer.

But on the other hand I respectfully do not agree with your sentence "usually realizing it's a local issue". It has never been a local issue before in my previously reported bugs. I always tried to provide as much information as I could gather and I followed the bug reporting guidelines to the letter.

Moving on, I did read the logcats but admittedly my knowledge of Android architecture and of the project's ongoing development is very limited at the moment, so I did not spot the GNSS HAL update issue right away.

I will make sure to always perform a clean build first before reporting any further bugs in the future.
Many thanks for your help and for your work on the project, it's much appreciated.

**Comment by MarijnS95** [comment]
It is fine to use this project as a user and we are deeply grateful for those spending their valuable time using this project, which basically means aiding in testing and reporting as we are with a far too small for the 20-or-so maintained devices. I personally should perhaps not be expecting each and every one to look at the logs, even if this is a developer-minded project (having to build it yourself, no easy-to-use downloads provided).

> I respectfully do not agree with your sentence "usually realizing it's a local issue". It has never been a local issue before in my previously reported bugs.

This is a statement in general, not specifically aimed at your reports. My fault for bringing it up here.

> so I did not spot the GNSS HAL update issue right away.

I would usually agree since the logs are massive, but in this case it's filled to the brim with the same error. Allow me to paste the last 22 lines:
```
05-30 07:30:35.025  7160  7160 E vndksupport: Could not load /vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so from default namespace: dlopen failed: cannot locate symbol "_ZN8loc_core14LocDualContext16mLocationHalNameE" referenced by "/vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so"....
05-30 07:30:35.026  7160  7160 E ServiceManagement: Failed to dlopen android.hardware.gnss@1.1-impl-qti.so: unknown error
05-30 07:30:35.026  7160  7160 E android.hardware.gnss@1.1-service-qti: Could not get passthrough implementation for android.hardware.gnss@1.1::IGnss/default.
--------- switch to kernel
05-30 07:30:35.030     0     0 I init    : Service 'gnss_service' (pid 7160) exited with status 1
05-30 07:30:35.030     0     0 I init    : Sending signal 9 to service 'gnss_service' (pid 7160) process group...
05-30 07:30:35.030     0     0 I libprocessgroup: Successfully killed process cgroup uid 1021 pid 7160 in 0ms
05-30 07:30:35.030     0     0 E init    : updatable process 'gnss_service' exited 4 times before boot completed
05-30 07:30:35.031     0     0 E init    : Init cannot set 'ro.init.updatable_crashing_process_name' to 'gnss_service': Read-only property was already set
05-30 07:30:35.031     0     0 E init    : Init cannot set 'ro.init.updatable_crashing' to '1': Read-only property was already set
--------- switch to main
05-30 07:30:35.462  6479  6479 W ServiceManagement: Waited one second for android.hardware.gnss@2.0::IGnss/default
05-30 07:30:35.464  6479  6479 I ServiceManagement: getService: Trying again for android.hardware.gnss@2.0::IGnss/default...
--------- switch to kernel
05-30 07:30:35.467     0     0 I init    : Received control message 'interface_start' for 'android.hardware.gnss@2.0::IGnss/default' from pid: 492 (/system/bin/hwservicemanager)
05-30 07:30:35.467     0     0 E init    : Could not find 'android.hardware.gnss@2.0::IGnss/default' for ctl.interface_start
--------- switch to main
05-30 07:30:36.466  6479  6479 W ServiceManagement: Waited one second for android.hardware.gnss@2.0::IGnss/default
05-30 07:30:36.469  6479  6479 I ServiceManagement: getService: Trying again for android.hardware.gnss@2.0::IGnss/default...
--------- switch to kernel
05-30 07:30:36.471     0     0 I init    : Received control message 'interface_start' for 'android.hardware.gnss@2.0::IGnss/default' from pid: 492 (/system/bin/hwservicemanager)
05-30 07:30:36.471     0     0 E init    : Could not find 'android.hardware.gnss@2.0::IGnss/default' for ctl.interface_start
```
Let's give it the benefit of the doubt: I don't want to be the starter of yet another flamewar on GH.

> I will make sure to always perform a clean build

Just to be absolutely sure: use `make installclean`. Cleaning the full build is a waste of time (on ThreadRipper a waste of energy), and I have _never_ needed to do that, _ever_. I only do it at random if I assume there's a lot of unused/renamed stuff sitting around. `installclean` is the way to go since the build system packages everything in the vendor/system/root directories rather than collecting only what is specified in the device tree. It's a quick command to run and prevents all such issues.

**Comment by xperia10dev** [comment]
I was definitely not trying to provoke any flamewars, or waste anyone's time with the initial bug report. 

Again, I did see the logcat lines you are referring to, but due to my limited knowledge I did not expect the device to remain at the boot logo due to a GNSS-related error (more like only the Location service would fail). So I wrongly assumed it must have been something else which caused the boot failure, hence the report.

Thanks for the `make installclean` tip, it will surely help with my old hardware.

**Comment by MarijnS95** [comment]
> I was definitely not trying to provoke any flamewars, or waste anyone's time with the initial bug report.

I would be the one to provoke that flamewar, even if there's no point debating whether you should or should not have noticed the same service crashing over and over again (as in some cases that isn't even the root cause). I digress, let's not go this route and instead turn it into a constructive learning moment:

> Again, I did see the logcat lines you are referring to, but due to my limited knowledge I did not expect the device to remain at the boot logo due to a GNSS-related error (more like only the Location service would fail). So I wrongly assumed it must have been something else which caused the boot failure, hence the report.

Debugging boot dependencies can be tough and require hands-on experience; and in this case be aware of recent changes too. As I cannot reasonably expect anyone to have that, let's see how we could look at this log:

First up, we repeatedly see this:
```
Received control message 'interface_start' for 'android.hardware.gnss@2.0::IGnss/default' from pid: 492 (/system/bin/hwservicemanager)
05-30 07:30:35.467     0     0 E init    : Could not find 'android.hardware.gnss@2.0::IGnss/default' for ctl.interface_start
```
That means something is _actively_ trying to get to the IGnss interface, but no initrc file specifies an interface to lazy-start it. Usually meaning it should already be started by a normal `service` declaration.
Since this keeps on repeating, it is likely a requirement for Android to fully boot up.

Key is to figuring out _why_ gnss doesn't start. Since `service`s are automatically restarted on crash (as long as they aren't `oneshot`) logs for this usually aren't far away:
```
05-30 07:30:34.970     0     0 I init    : starting service 'gnss_service'...
--------- switch to main
05-30 07:30:35.025  7160  7160 E vndksupport: Could not load /vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so from default namespace: dlopen failed: cannot locate symbol "_ZN8loc_core14LocDualContext16mLocationHalNameE" referenced by "/vendor/lib64/hw/android.hardware.gnss@1.1-impl-qti.so"....
05-30 07:30:35.026  7160  7160 E ServiceManagement: Failed to dlopen android.hardware.gnss@1.1-impl-qti.so: unknown error
05-30 07:30:35.026  7160  7160 E android.hardware.gnss@1.1-service-qti: Could not get passthrough implementation for android.hardware.gnss@1.1::IGnss/default.
```
Great, the reason is very clear! Usually it is a missing file or symbol, something stupid like that. But in this case, notice how we requested `@2.0` (and didn't get an error about that _not_ being in the manifest) and now see the HAL trying to start at `@1.1`?
(Bonus: In this case the old service uses the same libraries as the new ones, which have been recompiled for 2.0 with changed functionality. That makes them incompatible resulting in the linker error -> another hint at the mismatch :slightly_smiling_face: )

From that point there are multiple ways to approach the issue and/or make a bug report: Check the directory whether more versions are available, and check sonyxperiadev for recent changes. You learned about `make installclean` which can be applied in this case, but otherwise a bug report à la "Sonyxperiadev switched to GNSS 2.0 but it still includes 1.1" or "GNSS service version mismatch" would be totally accepted by me.

**Takeaway:** Repeatedly seeing the same error on a "stuck" device is in 99.9% of the cases the lead towards the issue. Showing in a bug report that you have identified this lead (and perhaps followed its trail for a while) but are not sure whether it's correct or how to proceed goes a long way to show the effort put in: even if it takes minutes at most.
Also, notice all these issues have millions of variations, the joy is being able to identify and figure them out as they come :grin: 

> Thanks for the `make installclean` tip, it will surely help with my old hardware.

Let me try to get a section in the build guide how to rebuild using this. There's currently nothing at all detailing how to do this, and I blame it on AOSP for blindly trusting the stuff in the image folders (and relying on projects to specify `CleanSpec.mk` for _everything_. Ugh).

I hope that clears it up and aids with the next issue :slightly_smiling_face:  And again apologies for (re)starting off on the wrong foot: I wasn't sure whether you didn't read logs at all or wasn't sure what the issue could be, and assumed the worst.

**Comment by xperia10dev** [comment]
Thanks for the detailed explanation about the boot process and how to identify the errors. It will definitely come in handy next time.

About the how-to for rebuilding, what I have been doing until now to avoid starting from scratch each time a new tag comes along (usually monthly) is the following (surely it is by no means a complete or even correct list, no one else should try to follow these steps verbatim):

- `cd ~/android`
- `repo status` and discard or stash local modifications (e.g., patches to disable Metalava checks and to only build the kernel for my device)
- `pushd .repo/local_manifests`
- `git pull`
- `git checkout android-10.0.0_rXY`
- `popd`
- `repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_rXY`
- `./repo_update.sh`
- reapply stashed local modifications if needed
- `source build/envsetup.sh && lunch aosp_i4113-userdebug`
- build kernel if needed: `pushd kernel/sony/msm-4.14; ./build-kernels-clang.sh; popd`
- `make installclean` **<- this step added today**
- `make`

**Comment by MarijnS95** [comment]
@xperia10dev Neat, that's indeed the simple and sane way to do it :)

**Comment by RahifM** [comment]
hello there @MarijnS95, i had a question about the make installclean command like can it be used when shift build arch? like i do a build on arm64 device and then do make installclean and do for arm32 device will it cause issues?

**Comment by MarijnS95** [comment]
@RahifM Those cases should be totally separate as the devices are built in different subfolders, eg. `out/target/product/your-aarch64-device` and `out/target/product/your-arm-device`. Installclean only cleans directories and images in those folders, anything outside of that should be generic (™) and things of other devices should never be touched.

**Comment by RahifM** [comment]
oh i see, thanks for the info :)
