### ISSUE TITLE
${SECONDARY_STORAGE} returns null

### ISSUE THREAD

**Issue by Gouster4** [sonyxperiadev/bug_tracker#605]
**Platform:tama** 
**Device:akari** 
**Kernel version:4.14** 
**Android version10:** 
**Software binaries version:v8** 

**Previously working on**
Never tryed before

**Description**
${SECONDARY_STORAGE} returns null (nothing), but should return path to SD card (that one in slot, not emulated)

**Symptoms**
${SECONDARY_STORAGE} returns null

**How to reproduce**
echo ${SECONDARY_STORAGE}
From terminal

**Comment by Gouster4** [comment]
${EXTERNAL_STORAGE} returns path for emulated sd, as excepted..

**Comment by Haxk20** [comment]
I'm sorry but i don't see a reason why we should have 2 variables containing the same exact path.
If this is an issue with some app you are using i would recommend contacting the developer of that application.

If this isnt an issue with application then you can easily add this variable in one of the init scripts.

**Comment by MartinX3** [comment]
It seems that the `SECONDARY_STORAGE` is used for external storages (not the internal one or the internal sdcard at `EXTERNAL_STORAGE`.

And yes, if you need it, you should add it into an init script.
By default android devices don't use external storages outside of the device.

**Comment by MarijnS95** [comment]
`SECONDARY_STORAGE` seems to be an old deprecated environment variable (set by Android, has NOTHING to do with SODP) for retrieving this path. See for example https://android-review.googlesource.com/c/platform/frameworks/base/+/681963.

The relevant app should rather use newer storage and/or environment APIs for this. If using it from termux or another terminal emulator they perhaps redefine or provide this functionality elsewhere; otherwise open a question on their side.

Feel free to close this, it is not related to SODP nor can (and should!) we do anything about it.

**Comment by Gouster4** [comment]
Found solution...
`export SECONDARY_STORAGE="$(ls /storage | grep -v '^self$' | grep -v '^emulated$')"`
