### ISSUE TITLE
[4.14][10][yoshino][maple]Can't wake phone from sleep

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#621]
**Platform:** yoshino
**Device:** maple
**Kernel version:** 4.14
**Android version:** 10
**Software binaries version:** `10.0.7.1_r1_v9c_yoshino`

**Previously working on**
Has this always been a problem, or is it a new issue?
Before simular issue: https://github.com/sonyxperiadev/bug_tracker/issues/590

**Description**
Boot the device, before enter unlock screen, plug the power in,  
then everything will be fine, can let screen turn off, then turn on.

Once unplug the power for a while  
(I trust the phone are start trying to sleep to reduce battery consume)
then press power button to wake the phone, the screen just crash and can't display anything.

**Symptoms**
Once the device go into sleep mode, display can't restore.

**How to reproduce**
- Boot
- Plug power before unlock interface, during boot animation
- Press power button to switch display on or off, to confirm everything is fine right now
- Unplug power
- Press power button to turn off display
- Wait 30~60 second, or wait until phone is sleep
- Press power button to see screen crash

**Additional context**
Can't extract the log...
I read these:
> You can get them via adb pull /sys/fs/pstore
> 
> Additional boot the system while connected to USB and execute following commands:
> adb logcat >logcat.log
> Press Ctrl+C after you have logged in to your phone and waited lets say ten seconds
> Do as well a:
> adb shell dmesg >dmesg.log

But I need to unplug the phone to trigger the bug,  
once unplug, adb will not work.  
After crash-reboot, `adb pull /sys/fs/pstore` copied an empty folder contains nothing.  
I should try adb over network to see if I can catch the log during screen crash later

**Comment by stefanhh0** [comment]
@mhtvsSFrpHdE please let us know on which kernel commit you are (`adb shell uname -r`)

In case you are running the prebuilt kernel (commit: e979699d5913064a7fb67e624b6221f5838416cd) or any other older kernel before PR https://github.com/sonyxperiadev/kernel/pull/2322/ please build the latest kernel and retest.

**Comment by mhtvsSFrpHdE** [comment]
@stefanhh0 I get
```
4.14.186-ge979699d59130-dirty
```

**Comment by mhtvsSFrpHdE** [comment]
I use
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices

So I'm using a pre-built kernel which is may not update to latest.
And I should go with this and give a try...
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices

**Comment by mhtvsSFrpHdE** [comment]
Well what a error...
```
> rm -r device/sony/common-kernel
rm: cannot remove 'device/sony/common-kernel': No such file or directory

> ls device/sony
akari     bahamut    ganges   kumano  mermaid  pioneer  sepolicy  yoshino
akatsuki  common     griffin  lilac   nile     poplar   tama
apollo    discovery  kirin    maple   pdx201   seine    voyager
``

**Comment by mhtvsSFrpHdE** [comment]
Do some random try
```
> find ./ -name "common-kernel"
./kernel/sony/msm-4.14/common-kernel

> rm -rf ./kernel/sony/msm-4.14/common-kernel
```

**Comment by stefanhh0** [comment]
Yes, indeed that is the old prebuilt kernel. The guide is a little bit outdated.

You should use instead my script: https://github.com/stefanhh0/aosp-10/blob/master/build-4.14.sh or copy the parts responsible for building the kernel.

```
SOURCE=${SOURCE:-~/android/source}
APK_DIR=${APK_DIR:-~/android/apk}
LUNCH_CHOICE=${LUNCH_CHOICE:-aosp_g8441-userdebug}
PLATFORM=${PLATFORM:-yoshino}
DEVICE=${DEVICE:-lilac}

pushd kernel/sony/msm-4.14/common-kernel
    _platform_upper=`echo $PLATFORM|tr '[:lower:]' '[:upper:]'`
    sed -i "s/PLATFORMS=.*/PLATFORMS=$PLATFORM/1" build-kernels-clang.sh
    sed -i "s/$_platform_upper=.*/$_platform_upper=$DEVICE/1" build-kernels-clang.sh
    find . -name "*$DEVICE*" -exec rm "{}" \;
    bash ./build-kernels-clang.sh
popd
```

replace the DEVICE and LUNCH_CHOICE accordingly.

Afterwards you just have to call:
`make bootimage`

**Comment by mhtvsSFrpHdE** [comment]
Done with it, but after `fastboot flash boot boot.img`, the issue remains.  
adb shows
```
4.14.186-ge979699d59130-dirty
```
The version hasn't change. I try the `build-4.14.sh`.

**Comment by stefanhh0** [comment]
Not sure what went wrong then, I am using the snippets myself often and they should also work for maple
Please be aware that the script is pulling in opengapps, additionally you don't have to change the script itself but you can just call it as follows to build everything for maple:
`env LUNCH_CHOICE=aosp_g8141-userdebug PLATFORM=yoshino DEVICE=maple ./build-4.14.sh`
resp. for g8142:
`env LUNCH_CHOICE=aosp_g8142-userdebug PLATFORM=yoshino DEVICE=maple ./build-4.14.sh`

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> Not sure what went wrong then, I am using the snippets myself often and they should also work for maple
> Please be aware that the script is pulling in opengapps, additionally you don't have to change the script itself but you can just call it as follows to build everything for maple:
> `env LUNCH_CHOICE=aosp_g8141-userdebug PLATFORM=yoshino DEVICE=maple ./build-4.14.sh`
> resp. for g8142:
> `env LUNCH_CHOICE=aosp_g8142-userdebug PLATFORM=yoshino DEVICE=maple ./build-4.14.sh`

@stefanhh0 I didn't realize I need to `DEVICE=maple`, processed and wait for build.

**Comment by stefanhh0** [comment]
Yes, platform and device is required, else it will build the default kernel, that is for lilac. The script could be smarter but I would have to figure out how to deduct platform and device from the lunch choice...

**Comment by MarijnS95** [comment]
If this runs within a `lunch`ed environment, `get_build_var PRODUCT_DEVICE`?

**Comment by mhtvsSFrpHdE** [comment]
@stefanhh0 I have question  
Until now all I did is follow the official guide,  
but got "unexpected" results with random build failed(need to wait for hours then update ropository again to see if the error disappears).

Your script did...some...I would call hidden tricks, to success the build with latest patch, which is official guide not.

So now if we are recommended to use this script instead of official guide,  
then link this script on the official guide should be better to let new one to know "Oh I'm not going to type the commands, just use script after repo sync" to get a constant, correct build? I mean, the as close as possible how Sony maintainers to build the system.

**Comment by mhtvsSFrpHdE** [comment]
```
4.14.188-g725e208b4da0-dirty
```
With this build, no wake-display-crash!  
Thank you!

**Comment by stefanhh0** [comment]
@MarijnS95 Great! Thanks for giving me that hint. Now the platform and device vars are retrieved from the build env. Which simplifies the script for the users and avoids specifying something inconsistent.

@mhtvsSFrpHdE I am happy to hear that with the newer kernel the problem has been fixed.

Regarding your comment https://github.com/sonyxperiadev/bug_tracker/issues/621#issuecomment-665240613:
There are no hidden tricks in the script. The clear advantage this script has in comparison to the official build is, that the script builds the latest kernel always and that way all the already fixed problems in the kernel are gone as soon as it is available in the kernel and one does not have to wait until the pre-built kernels are updated. However when the script is being run in a not ideal point in time it runs into the very same problems as you probably have experienced in the past. Sometimes changes are interdepending between repos and there is then a time-gap where the repos are inconsistent because things can't be merged back atomically. Also sometimes during integration it turns out something was de-stabilized that needs to be fixed, then also the build result won't be nice. From my experience it is safest to sync sources when the development and integration phase cooled down, that is usually the case after 18:00 CEST weekdays. Also weekends are good time to sync sources. Also sometimes it is good to see if there are PRs (Pull Requests) available that could help fixing a problem.

To speed up builds I just recently learned that it is most of the time not required to build everything from scratch. Doing a `make installclean` instead of a `make clean` helps a lot saving a huge amount of time and energy.

My script kind of integrates all what I have learned and helps me sometimes to cherry-pick fixes very easily. Also it builds aosp like I want to have it, so it is adopted to my personal preferences, which makes it not suitable for being integral part of the official sony build guide. However if you want to continue using that script I am happy to see that and if you want to provide feedback and/or suggest changes you can always do it here: https://github.com/stefanhh0/aosp-10/issues

**Comment by mhtvsSFrpHdE** [comment]
@stefanhh0 As you can see, I did follow the official kernel build guide but I still got an old version kernel.  
I need some time to read script and figure out what are the difference...  

Past few hours I did test about custom recovery in order to install magisk, camera and sensors...  
I haven't met other issue yet, cheers!

**Comment by stefanhh0** [comment]
@mhtvsSFrpHdE The kernel build guide is outdated, it can't be used anymore for aosp 10 and kernel 4.14 it will be updated.

Following steps are done by the script:

1. Adjust `build-kernels-clang.sh` to only build a single kernel for the current device/platform combination
2. Delete the pre-built kernel image from kernel/sony/msm-4.9/common-kernel
3. Build the kernel via `build-kernels-clang.sh` call

Then with `make bootimage` you can build the boot image picking the newly created kernel from `kernel/sony/msm-4.9/common-kernel`
