### ISSUE TITLE
[dora]Usb otg not working at all

### ISSUE THREAD

**Issue by Paulbouchara** [sonyxperiadev/bug_tracker#65]
Platform: Tone (maybe more)
Device: Kagura (sure) | all?
Kernel version: 4.4
Android version: 8.0

Description:
When I use Usb otg cable, the device can't recognize anything. Tested with :
Mouse, keyboard, Headset, usb key, iPhone (yeah I know)

How to reproduce:
Well, just flash a recent aosp image, and it should appear.
OSS/kernel side suspected.

No logs for now, I'll create them when possible

**Comment by jamuir** [comment]
Does the Emma image for kagura support OTG?  Some devices to do not support
it.

On Dec 30, 2017 10:57 AM, "Paulbouchara" <notifications@github.com> wrote:

Platform: Tone (maybe more)
Device: Kagura (sure) | all?
Kernel version: 4.4
Android version: 8.0

Description:
When I use Usb otg cable, the device can't recognize anything. Tested with :
Mouse, keyboard, Headset, usb key, iPhone (yeah I know)

How to reproduce:
Well, just flash a recent aosp image, and it should appear.
OSS/kernel side suspected.

No logs for now, I'll create them when possible

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sonyxperiadev/bug_tracker/issues/65>, or mute the thread

**Comment by Paulbouchara** [comment]
The Emma stock firmware support otg only in a weird way, 
I connect headset, turning on, no audio output
Usb key, not detected, but (surprise) an iPhone gets detected and recognized.
On aosp tho, no detection at all

**Comment by Paulbouchara** [comment]
Confirmed kernel issue, this cause android auto not working at all

**Comment by Paulbouchara** [comment]
Confirmed kernel issue, this cause android auto not working at all

**Comment by jerpelea** [comment]
the bug is confirmed on all tone devices

**Comment by jerpelea** [comment]
@kholk ?

**Comment by kholk** [comment]
Will verify asap. I find it seriously strange for it to not work, as I remember testing it some months ago on 5.7.r1. Perhaps something broke it.

**Comment by jerpelea** [comment]
@kholk

**Comment by jerpelea** [comment]
confirmed 
not working on 5.7.r1

**Comment by jerpelea** [comment]
tested devices 
dora - broken
kugo - broken
lilac - OK
maple - OK

**Comment by oshmoun** [comment]
@jerpelea kugo isn't broken, just tested here
input devices work
storage devices don't, but they're still detected in kernel, the storage devices probably need some fix in userspace.
so loire is not affected by this issue.

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/device-sony-loire/commit/509bc13870311a92317d06fb89884021aca3176a

**Comment by oshmoun** [comment]
kagura has been fixed as well not, confirmed by @Paulbouchara 
keyaki still does not, and dora is untested after https://github.com/sonyxperiadev/kernel/pull/1575

**Comment by jerpelea** [comment]
kagura - OK
sonyxperiadev/kernel#1575

keyaki - OK
fix: https://github.com/sonyxperiadev/kernel/commit/709a748518349d740b7d2160330af15843e39781

**Comment by jerpelea** [comment]
dora - not working

**Comment by kholk** [comment]
Solution in this PR:
https://github.com/sonyxperiadev/kernel/pull/1585

Enjoy!

**Comment by jerpelea** [comment]
dora - Ok
