### ISSUE TITLE
Camera too bright and noise compared to closed source system

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [sonyxperiadev/bug_tracker#668]
**Platform:*yoshino* 
**Device:*maple* 
**Kernel version:*4.14* 
**Android version:*Android 10* 
**Software binaries version:*v11c* 

**Previously working on**
Has this always been a problem, or is it a new issue?
always since first time I try open device project.

**Description**
I have two Xperia XZ Premium, one is open device system, one is not unlocked and running latest Sony Pie ROM.  
I use Camera2 API and set exposure time to 1/50 second with ISO 200, in a relatively low in-room LED light environment. The open source camera takes very light photo and more noisey with exact same argument.

So result in Xperia XZ Premium is installed IMX 400 sensor, but with open source approch, the photo quality is much lower than IMX 298 on open source One plus 3T.

These days I'm looking for IMX 363 & Pixel 2 for a test, but still hope can get a normal functionllly IMX 400.

In addition, on very high ISO value like ISO 800 and 1/70 exposure time, the camera focus will not work properly, specify a focus point then will get blur photo. Other difference is close source system have a range of 50 to 3200 ISO, but open source system only 50 to 800.

**Comment by sraase** [comment]
The camera implementation between Open Devices and Sony Xperia software is completely different. Open Devices only provides basic camera support, so limitations and lower quality are normal.

**Comment by sbourdeauducq** [comment]
So, which phone manufacturer should we choose to avoid this sort of problem?
I actually bought a Sony phone just because of Open Devices, but this and many other bugs such as #666 are disappointing.

**Comment by sraase** [comment]
I am biased and will therefore not answer this question.

**Comment by chris42** [comment]
> So, which phone manufacturer should we choose to avoid this sort of problem?
> I actually bought a Sony phone just because of Open Devices, but this and many other bugs such as #666 are disappointing.

If you are looking for an AOSP phone that is just as good as stock out of the box, you will find none. AOSP is not a open replacement for devices with the same functionality like stock ROMs. It is the base for every other ROM, hence is limited in features and quality already. For every improvement the community is needed to build something. Hence the "quality" of the AOSP based phone depends on how many people use and develop for the phone.

So if you want a no involvement and an out of the box good AOSP based ROM take the phone with the biggest development community and user-base.

**Comment by sbourdeauducq** [comment]
> If you are looking for an AOSP phone that is just as good as stock out of the box, you will find none. AOSP is not an open replacement for devices with the same functionality like stock ROMs. It is the base for every other ROM, hence is limited in features and quality already.

Feature I can perhaps understand, but quality? Why is AOSP brimming with *bugs*? Why isn't there a clean and modular process for manufacturers to add features to AOSP?

> So if you want a no involvement and an out of the box good AOSP based ROM take the phone with the biggest development community and user-base.

No, large community does not mean quality.

**Comment by chris42** [comment]
Because every bug needs to be solved by someone. No hands no cookies. A large community does not mean automatically better quality, but it allows for it. If you do not have the resources to maintain dozens of devices (like the open device program) 
you can't do anything about it.

It is the old open source / community driven development dilemma. All this is done by volunteers hence you cannot expect anything. 
Info: The open device program is supported by Sony only via the binaries and some organisational stuff, the device maintenance is fully done by community members.

Regarding AOSP: Any manufacturer (including google) can contribute to the AOSP code easily, but it is not in their interest. They want to have an advantage to their competitors. So sharing features or quality improvements with them does not make sense.

I understand the frustration if things are not working or not doing well in comparison to stock features, however this is the reality for most community driven projects that lack developers and supporters.

**Comment by sbourdeauducq** [comment]
Okay, no need to buy Sony phones again then...

**Comment by Haxk20** [comment]
> > If you are looking for an AOSP phone that is just as good as stock out of the box, you will find none. AOSP is not an open replacement for devices with the same functionality like stock ROMs. It is the base for every other ROM, hence is limited in features and quality already.
> 
> Feature I can perhaps understand, but quality? Why is AOSP brimming with _bugs_? Why isn't there a clean and modular process for manufacturers to add features to AOSP?
> 

As chris said above. Every single OEM can add features or fix bugs in AOSP. And this isnt even AOSP bug. This is SODP bug.
To fix such issues it takes time. Time that many of us sadly dont have.
People usually just think we do this full time or are even paid. Thats not the case at all. We do this because we want to and we get only good feeling from it. We also have our personal lives which we have to take care off.
And even if all of us had all the time in the world to only contribute to SODP we would probably still have some minor bugs.
That is because there isnt thousands of us.
There is 5 of us that contribute to the project often and like 12 or so people (Including the 5 people mentioned before) who contribute only from time to time.

**Comment by Haxk20** [comment]
> Okay, no need to buy Sony phones again then...

Then very good luck to you actually finding a phone that runs pure AOSP without any sort of bugs. Because there are ALWAYS bugs.

**Comment by Haxk20** [comment]
And yes we are aware that it is quite stressing to have some bugs. But honestly the camera works. You can take pictures and record video.

We have around 10 platforms to support which when counting all the devices from them is around 40+ devices that we support.
We cant spend hours upon hours tuning the camera to be perfect like sony does with their devices. Yes SONY actually tunes the profiles for each camera until it meets their standards.

**Comment by sbourdeauducq** [comment]
Okay, sorry, I see.
I'm not blaming volunteers, but rather Google and phone manufacturers here.

> Then very good luck to you actually finding a phone that runs pure AOSP without any sort of bugs. 

Certainly, but the competition often has better specs than Sony for the price; SODP (and several alternative ROMs though they also turned to be a disappointment) was the major selling point for me. In fact, I'd be ready to pay many times the price for a phone that has a mostly bug-free AOSP.

> We cant spend hours upon hours tuning the camera to be perfect like sony does with their devices. Yes SONY actually tunes the profiles for each camera until it meets their standards.

Fair enough, but Sony probably should just release that tuned code then, instead of having two versions. I don't think it would run on competitors' hardware anyway?

**Comment by Haxk20** [comment]
> Okay, sorry, I see.
> I'm not blaming volunteers, but rather Google and phone manufacturers here.
> 
> > Then very good luck to you actually finding a phone that runs pure AOSP without any sort of bugs.
> 
> Certainly, but the competition often has better specs than Sony for the price; SODP (and several alternative ROMs though they also turned to be a disappointment) was the major selling point for me. In fact, I'd be ready to pay many times the price for a phone that has a mostly bug-free AOSP.
> 
> > We cant spend hours upon hours tuning the camera to be perfect like sony does with their devices. Yes SONY actually tunes the profiles for each camera until it meets their standards.
> 
> Fair enough, but Sony probably should just release that tuned code then, instead of having two versions. I don't think it would run on competitors' hardware anyway?

Its their own source. And its not 2 different versions. Its 2 totally different things. They have their camera HAL which is fully closed sourced and developed fully by them. What we use is the open-source camera HAL from CAF. 
And if SONY released their closed source camera HAL maybe some phones would not be able to use it but the point is that they spent lot of money on tuning their HAL to really good state. If they release this then other OEMs would see what magic they did to get such good camera.

As you can guess this is not what they want to do at all as it would be bad for them.

**Comment by mhtvsSFrpHdE** [comment]
@sbourdeauducq Before I enter SONY world, I had Nexus 4, Nexus 5X, Nexus 6P
after XZ Premium, I moved to Pixel 3.

The Nexus and Pixel are very adapted for AOSP, they are too good in this area,  
so that, I don't have an imagination about what if  the term "Open" is just a kind of deceptive advertising.

Now I have, I will add more vigilance on choosing open device, thanks to SONY's no help.  
I'm not judging the contributors guys, I mean SONY just not provided what they should do, after they told us, "Open".

You are except a SONY open device has same quality than Google's, but it's not.  
SONY do provide the source code, and if you don't have the ability to add every patch happens on Google devices,  
I suggest we just stick with Google.

**Comment by sbourdeauducq** [comment]
@mhtvsSFrpHdE yeah, I recently simply got a second hand Pixel 3 for $80 and got rid of this problem and many others. Runs GrapheneOS without any major bugs.
