### ISSUE TITLE
[4.14][AOSP11][pdx201/Seine] updatable process 'vendor.ims_rtp_daemon' exited 4 times in 4 minutes

### ISSUE THREAD

**Issue by egorovandreyrm** [sonyxperiadev/bug_tracker#682]
**Platform: AOSP** 
**Device: Xperia 10 II** 
**Kernel version: 4.14** 
**Android version: 11** 
**Software binaries version: SW_binaries_for_Xperia_Android_11_4.14_v3a_seine.img** 

I'm getting ims_rtp_daemon errors in logcat.

log: [ims_rtp_daemon.txt](https://github.com/sonyxperiadev/bug_tracker/files/6097460/ims_rtp_daemon.txt)

Please advice.

**Comment by ix5** [comment]
Have you re-tried with newest (v4) binaries and the updates to device-sony-common?

**Comment by sony-seine-mirror** [comment]
this particular issue is fixed most probably but now I see other weird stuff in the log. 

It seems you are not testing the code before pushing it to the repository.

**Comment by Haxk20** [comment]
> this particular issue is fixed most probably but now I see other weird stuff in the log.
> 
> It seems you are not testing the code before pushing it to the repository.
> 
> Sorry. Wrong account. I created this account to mirror all your stuff and stop you from breaking my builds. The last time you just deleted the branch that the local_manifest project was referring to.

The Android 11 development here is still in full swing and thus a lot of changes happen.
We are sorry that we broke your build but well it happens.
One advice tho. Instead of being sassy next time in github comment when your build breaks maybe try to report an issue here that the build is broken ;)

**Comment by MarijnS95** [comment]
> It seems you are not testing the code
> [..]
> and stop you from breaking my builds

Fwiw playing the blame-game on a massively understaffed _open source_ project has never helped anyone - if anything it makes the few remaining souls flee in agony. **Actively** testing, reporting, _and if possible fixing + PR'ing_ does!

The main culprit here is not Android 11 (in fact, not at all, thanks to HIDL/binder/project treble these upgrades are really smooth) but the moving around of black boxes in the forms of "open source" (but massively complicated) HALs and their closed source counterpart found in the odm image. We're changing these to build _all maintained devices_ (including the new Edo platform) from the same unified codebase to suffer minimal maintainer hassle, but that sometimes comes at the risk of not merging everything at exactly the right time resulting in race conditions where you synced at the wrong moment and ended up with a slightly malfunctioning build.

That said a crashing service isn't too bad if it doesn't break anything else for you (ie. if not using IMS), the phone will still suspend and not consume much if any extra battery.

Finally we're resolving this situation by introducing more staging branches, in hopes of keeping the branches in manifests working while still being able to contribute, share, review and merge in-progress patches. Note that this comes as yet more overhead for this minuscule team, but alas.

**Comment by egorovandreyrm** [comment]
I'm sorry if my comment sounded rude.

And yes, I helped to fix not working wifi/mobile data issue but in one week you broke the build again by merging code into master without testing (I guess).

If we can have a stable branch, it will be just awesome. Currently, the master branch is like dev.

**Comment by Haxk20** [comment]
> I'm sorry if my comment sounded rude.
> 
> And yes, I helped to fix not working wifi/mobile data issue but in one week you broke the build again.
> 
> If we can have a stable branch, it will be just awesome. Currently, the master branch is like dev. 

Master is exactly what you just said. Its a development branch. Stable branch is r-mr1 for Android 11. Master is used for future android development and thus may be broken from time to time.

**Comment by MarijnS95** [comment]
> I'm sorry if my comment sounded rude.
> [...] you broke the build again.

Does not compute. By the way, who even cares about IMS when it needs _that many_ hacks and blobs to even start behaving, not to speak of working correctly at all? As a regular contributor I won't take blame for anything IMS related at all, it is a massive hack that attempts to undermine the longevity of mobile phones by working right against predefined interfaces like Treble and system/vendor boundaries in Java code.

Again: What is broken by seeing error messages in the logs? There are many, many more during normal operation, perhaps worth investigating those instead?

> If we can have a stable branch, it will be just awesome. Currently, the master branch is like dev.

We already have "stable branches" (eg. `q-mr1`, `r-mr1`), even though they will generally receive just as much if not more PRs. The "staging" (`master`!) branch is for new changes that _absolutely require_ odm updates and is generally used to share patches bringing up new platforms (Edo) without doing upfront build barriers when we don't know what's compatible with newer sources yet.

Unless you, right here, can to commit to testing every little change on ~18 devices, I nor anyone on this team is going to promise 100% reliability. That is - as explained - simply impossible to achieve with black-box blobs and CAF HALs intentionally built for compatibility with one and maybe few other SoCs. Stability can only be guaranteed if users actively test, review and provide feedback, instead of "you broke the build" blaming weeks later.

Another solution is mainline kernel support. No black boxes (everything is open source :scream:) and after initial bringup (lots to do!) and stabilization (things do break!) there is finally a point where end-users can sit on a slow-moving, stable branch, if preferred years behind state-of-the-art in hopes someone else did testing for them. But you can do the same here and now, use `q-mr1` and Android 10 blobs.

**Comment by jerpelea** [comment]
Discontinued Android version
