### ISSUE TITLE
[4.14][11][bahamut] "No rule to make target" with prebuilt dtc

### ISSUE THREAD

**Issue by voidanix** [sonyxperiadev/bug_tracker#689]
**Platform:** kumano 
**Device:** bahamut
**Kernel version:** 4.14
**Android version:** 11
**Software binaries version:** 

**Description**
I'm trying to build LineageOS for bahamut using SODP sources but when Image.gz-dtb must be generated, dtbo.img isn't being built with the prebuilt dtc (at `prebuilts/misc/linux-x86/dtc`) and the build fails; not tested with griffin so far

**Symptoms**
dtbo.img which is required is not being built, see log below

**How to reproduce**
1) Use SODP sources together with Lineage's (what I'm trying to achieve is something like the awesome work done by @MartinX3 [here](https://github.com/MartinX3-AndroidDevelopment-LineageOS), although with 18.1)

2) Give it a breakfast+brunch, or an `m -j$(nproc) bootimage` for the latter

3) Watch it crash and burn

**Additional context**
The way I was able to get around it is by tweaking `Customization.mk` and adding
```
TARGET_KERNEL_ADDITIONAL_FLAGS := \
	DTC_EXT=/usr/bin/dtc
```
then inside `kernel/sony/msm-4.14/kernel/scripts/Makefile.lib`:
```diff
-$(obj)/%.dtb: $(src)/%.dts $(DTC) FORCE
+$(obj)/%.dtb: $(src)/%.dts $(DTC_EXT) FORCE
```
I'm also using the hax for bison/flex as the build won't allow me to use them, the host is Fedora 34

Log:
```
make: Entering directory '/home/lol/android/lineage/kernel/sony/msm-4.14/kernel'
make[1]: Entering directory '/home/lol/android/lineage/out/target/product/bahamut/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     scripts/mod/devicetable-offsets.h
  Using /home/lol/android/lineage/kernel/sony/msm-4.14/kernel as source for kernel
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    /home/lol/android/lineage/kernel/sony/msm-4.14/kernel/scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
make[3]: *** No rule to make target 'arch/arm64/boot/dts/qcom/sm8150.dtb', needed by 'arch/arm64/boot/dts/qcom/sm8150-kumano-bahamut_generic-overlay.dtbo'.  Stop.
make[2]: *** [/home/lol/android/lineage/kernel/sony/msm-4.14/kernel/scripts/Makefile.build:679: arch/arm64/boot/dts/qcom] Error 2
make[1]: *** [arch/arm64/Makefile:224: dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/lol/android/lineage/out/target/product/bahamut/obj/KERNEL_OBJ'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory '/home/lol/android/lineage/kernel/sony/msm-4.14/kernel'
15:23:54 ninja failed with: exit status 1

#### failed to build some targets (01:01 (mm:ss)) ####
```

**Comment by MarijnS95** [comment]
This is not an SODP issue, we don't build kernels in-tree anymore since Android 10 disabled use of pretty much every executable not curated and allowed by Google.

Fwiw `Makefile.lib` already overrides `DTC` with `DTC_EXT` if found:

```makefile
ifneq ($(DTC_EXT),)
DTC = $(DTC_EXT)
else
DTC = $(objtree)/scripts/dtc/dtc
endif
```

Our "normal" prebuilt kernel build (outside of Android) builds `dtc` from the kernel tree and invokes it (`$(objtree)/scripts/dtc/dtc` here). This all happens automatically when `make` is invoked. The one in `prebuilts` is ancient: https://android.googlesource.com/platform/prebuilts/misc/+log/refs/tags/android-11.0.0_r34/linux-x86/dtc four years ago! Is this common practice in LineageOS :vomiting_face: or have they overriden it?

(Sidenote: `dtbo.img` isn't built by `dtc`, at least not directly. `dtc` compiles appended dtbs for `Image.gz-dtb` and `dtbo` files, which then use `mkdtboimg.py` or a variant thereof to create the image: https://github.com/MarijnS95/oot/blob/78b5a509d2e1f2716fdbef15ed887e53235fb984/create_images.sh#L18-L32)

**Comment by jerpelea** [comment]
please update your local build rules
