### ISSUE TITLE
[pdx201][AOSP11] Device not booting to recovery after installing OTA update when bootloader is locked

### ISSUE THREAD

**Issue by egorovandreyrm** [sonyxperiadev/bug_tracker#696]
**Platform:** pdx201 
**Device:** xperia 10 II
**Kernel version:** 4.14
**Android version:** 11 r36
**Software binaries version:**  SW_binaries_for_Xperia_Android_11_4.14_v5b

**Description**
I'm having a weird issue with the recovery partition (?) on my sony device. I'm not sure that the issue is related to Sony devices.

I can build and install ROM perfectly on my sony device and I can also lock bootloader without any problem. The device boots up and works well. 

If I try to install an OTA update, it installs without any errors/problems, and the device boots up and works properly.

That said, if I try to wipe it (factory reset from Settings), it tries to do it, fails, and ends up rebooting to the second slot.  The same thing happens if I try to reboot to recovery - it ends up booting to the second slot. 

**The problem does not occur if I do not lock the bootloader.**

This is how I sign the ROM:

`sign_target_files_apks \ `
`  -o \ `
`  --default_key_mappings certificates \ `
`  --avb_vbmeta_key certificates/prod/avb_encrypted.key \ `
`  --avb_vbmeta_algorithm SHA256_RSA4096 \`
`  out/dist/*-target_files-*.zip \`
`  signed-target-files.zip`

`img_from_target_files signed-target-files.zip signed-imgs.zip`

This is how I generate OTAs:

`ota_from_target_files -k certificates/releasekey signed-target-files.zip ota_update.zip`

When I flash a device, I flash both slots, avb, and lock the bootloader.

`fastboot set_active a/b`
`fastboot format userdata`
`fastboot -w update imgs.zip`

`avbtool extract_public_key --key certificates/avb_encrypted.key --output pkmd.bin`
`fastboot flash avb_custom_key pkmd.bin`

Please advice.

**Comment by MarijnS95** [comment]
What happens if you tell the device to reboot to recovery from fastboot (`fastboot reboot recovery` or `fastboot reboot fastboot`), does anything show up? This seems strange as recovery is - supposedly - self-contained again on PDX201 (thanks to SUPER partitioning) and beyond.

**Comment by egorovandreyrm** [comment]
#1: both slots are running version 1
#2: installed OTA and slot A running version 2
#3: rebooted to bootloader and run `fastboot reboot recovery`
#4: it tried to boot recovery, failed and loaded version 1 (switched slots).
#5: `fastboot reboot recovery` works fine now.
#6: if try switched slots back (`fastboot set_active a/b`), it is not booting anymore (switches back to the version 1 slot). 

Again. This behavior is only observed when bootloader is locked. Can it be signing issue?

**Comment by MarijnS95** [comment]
Whoops, please use `1.` format to get:

1. An automatic list;
2. Not ping/link issues number 1-6.

I presume you have flashed AOSP recovery, because of its shared dependency (with `boot`) on `dtbo`? It is indeed possible that that is guarded under different AVB keys, though that doesn't explain why `boot` remains working. `vbmeta` guards every partition except `system` (that's chained to `vbmeta_system`) but it might be that the bootloader is expecting something specific here that it doesn't for `boot`. Bootloaders are black-boxes, the only way to possibly get more info is by attaching a UART to the board and hoping it prints something interesting. I doubt kernel parameters are of interest here, but you never know.

**Comment by egorovandreyrm** [comment]
> I presume you have flashed AOSP recovery, because of its shared dependency (with boot) on dtbo?

I'd say yes. `fastboot -w update imgs.zip` flashes recovery and dtbo as far as I remember. To build target-files and images I use what is in the sony open device building tutorial. 

What confuses me is that until I flash the OTA, everything works just perfectly. Bootloader is locked, I can boot the device to recovery, wipe it, etc - which means that everything is fine with AVB and its keys/certificates, I reckon.
 
Installing OTA update breaks it somehow. I'm wondering if I'm not building OTA updates properly. I tried to look at the docs and code on github and did not find any clues to the issue.

**Comment by MarijnS95** [comment]
@egorovandreyrm That clarifies what I forgot to ask initially: this problem only surfaces on the _combination_ of flashing an OTA and locking the bootloader _afterwards_.

Are you always flashing the OTA through `fastboot update`, or do you have the ability to install the OTA from within booted Android (like stock and other ROMs)? I presume the OTA provides both an update to all images; ie. 

Since you're on a device with SUPER partitions, is the update flashed from "bootloader-fastboot" (blue LED, screen off) or "fastbootd" (screen on, looks like recovery, red text saying "fastbootD")? (must be the latter, bootloader-fastboot doesn't understand `SUPER`). We previously had wrong permissions where fastbootd was not allowed to flash all partitions, and IIRC this left some partitions unflashed, and goes unnoticed. You can perhaps try to flash the update from fastbootd, use the buttons to "continue to recovery", and use `adb` to extract `/tmp/recovery.log`.

---

It is however inexplicable why the updated slot fails booting afterwards, and why recovery starts working again (as per step 2./5. above). This sounds more like bootloader bugs than wrong OTA.

For the record most SODP developers (at least speaking for myself) flash images on their devices directly (easy to to, disabled AVB to perform on-device edits and tests) and are not as familiar with OTAs.

**Comment by egorovandreyrm** [comment]
> this problem only surfaces on the combination of flashing an OTA and locking the bootloader afterwards.

I locked the bootloader right after flashing version 1 to both slots. The very first step in the steps list above. I installed the OTA update when the bootloader was locked.

> Are you always flashing the OTA through fastboot update, or do you have the ability to install the OTA from within booted Android (like stock and other ROMs)? I presume the OTA provides both an update to all images; ie.

I can also install OTAs from booted Android using the update_engine API. I have the same problem in this case. `fastboot update` - I use `adb sideload` from recovery instead. 

> Since you're on a device with SUPER partitions, is the update flashed from "bootloader-fastboot" (blue LED, screen off) or "fastbootd" 

I flashed it from recovery using the `adb sideload` cmd.

> Recovery has an _a and _b partition too, which makes sense given that there's separate AVB for slot a and b, and both AVB images include boot and recovery. It is thus possible that one of the two slots "breaks", both booting into system and booting into recovery

Hmm, I'm probably flashing AVB to only one slot. I will try flashing it to both on Sunday. 

`fastboot set_active a`
`fastboot flash avb_custom_key pkmd.bin`
`fastboot set_active b`
`fastboot flash avb_custom_key pkmd.bin`

**Comment by egorovandreyrm** [comment]
`Hmm, I'm probably flashing AVB to only one slot. I will try flashing it to both on Sunday.`

That said, if the slot that can not boot recovery had the wrong AVB key, why did it boot the OS? I reckon if it had been the case, it would have refused to boot.

**Comment by MarijnS95** [comment]
> I can also install OTAs from booted Android using the update_engine API. I have the same problem in this case. `fastboot update` - I use `adb sideload` from recovery instead.
> 
> > Since you're on a device with SUPER partitions, is the update flashed from "bootloader-fastboot" (blue LED, screen off) or "fastbootd"
> 
> I flashed it from recovery using the `adb sideload` cmd.

Can you re-clarify if you ever managed to use `fastboot update` - and if that was from bootloader-fastboot or recovery-fastbootd? Or always used `adb sideload` from recovery instead?

> Hmm, I'm probably flashing AVB to only one slot. I will try flashing it to both on Sunday.

I doubt there are two AVB key slots, otherwise how could it have booted into Android previously? It seems the OTA managed to flash boot and AVB for one slot, but failed - or completely forgot about - `recovery`.

**Comment by egorovandreyrm** [comment]
> Can you re-clarify if you ever managed to use fastboot update - and if that was from bootloader-fastboot or recovery-fastbootd? Or always used adb sideload from recovery instead?

I always used adb sideload

**Comment by egorovandreyrm** [comment]
> It seems the OTA managed to flash boot and vbmeta for one slot, but failed - or completely forgot about - recovery.

I looked inside the ota package and it seems the package only has system, product and vendor partitions. 

Should I also include recovery to the OTA somehow? I quickly looked at ota_from_target_files documentation and did not find a way to do it. In AOSP master branch it supports custom_image argument but the android_r36 branch does not. I will investigate more on this but if you know the way, please share.

**Comment by MarijnS95** [comment]
I hope it includes `vbmeta` (and `vbmeta_system`) too, as that contains the hash-tree used to validate the image. Alternatively the usual vbmeta for bootloader-visible partitions (boot, recovery, dtbo) should be separate from system/vendor/product: https://source.android.com/devices/tech/ota/dynamic_partitions/implement#avb-configuration-changes. Either way if the OTA doesn't include recovery nor `vbmeta` that should remain bootable at least...

**Comment by jerpelea** [comment]
Discontinued Android version
