### ISSUE TITLE
NAGARA product.img cannot be flashed - no such partition available

### ISSUE THREAD

**Issue by floloescher** [sonyxperiadev/bug_tracker#806]
**Platform:Nagara** 
**Device:XQ-CT54** 
**Kernel version:** 
**Android version:13** 
**Software binaries version:** 

**Previously working on**
never worked

**Description**
After build of AOSP image following Building guide on Sony webpage, image cannot be flashed using fastboot flashall -w

**Symptoms**
Error Message: product.img cannot be installed - no such partition available.

**How to reproduce**
Build Common Kernal for Nagara, follow build guide and start to flash image with fastboot flashall -w
(other parts of the image such as recovery.img, ... are installed successfully before)

**Additional context**
Add any other context, e.g. upload logs or screenshots about the bug here.

**Comment by jerpelea** [comment]
Hi, 

Please note that not all partitions are available on all devices. 
Are you trying to flash the partitions in fastboot (blue led) or fastbootd (fastboot menu) mode?

Best regards
Alin

**Comment by floloescher** [comment]
Hi Alin, 
thanks for your fast response.
Did it after adb reboot bootloader = fastboot (blue led).
after adb reboot fastboot = fastbootd it did not work as "product needed for flash is pdx-223 (in Android-Info.txt). Even after renaming it from XQ-CT54 to pdx-223 did not work (then the first .img flash lead to an error). 
BR
Flo

**Comment by floloescher** [comment]
If it helps, could you provide me a list of the .IMG which are necessary to flash? I could try to flash them manually 1 after 1. 
boot.img
dtb.img
dtbo.img
product.img
ramdisk.img
ramdisk-recovery.img
recovery.img
system.img
system_ext.img
userdata.img
vendor.img
vendor_boot.img
vendor_boot-debug.img
vendor_boot-test-harness.img
vendor_ramdisk.img
vendor_ramdisk-debug.img
vendor_ramdisk-test-harness.img

**Comment by jerpelea** [comment]
Hi,

please follow the steps:
1. flash the device using flashtool with the latest Sony FW 
2. put the device in fastboot (blue led) 
3. type on the console (on the pc) fastboot reboot fastboot

After those steps  the device should be fastbootd menu which is mandatory to be able to flash the device

Best regards
Alin

**Comment by MarijnS95** [comment]
> Did it after adb reboot bootloader = fastboot (blue led).
> after adb reboot fastboot = fastbootd it did not work as "product needed for flash is pdx-223 (in Android-Info.txt). Even after renaming it from XQ-CT54 to pdx-223 did not work (then the first .img flash lead to an error).

That mis-name is intentional, so that `fastboot` can distinguish between bootloader-fastboot and recovery-fastboot (= `fastbootd`), and reboot in between. You are not allowed to flash SUPER partitions (`product`, `vendor`, `system` etc) in bootloader-fastboot because it doesn't know how SUPER partitions work.

**Comment by floloescher** [comment]
Ok, thank you MarijnS95. That is very helpful, but in no case covered in the aosp build / flash guide. 
Could you provide me source / instruction on how to flash the different .img to the device? 

Flash first super partitions in fastbootd first and other partitions in fastboot afterwards? Or the other way around? 
Any help is greatly appreaciated. 

Thanks!

**Comment by jerpelea** [comment]
you should flash all partitions from fastbootd

**Comment by MarijnS95** [comment]
> That is very helpful, but in no case covered in the aosp build / flash guide.

[The build guide](https://developer.sony.com/open-source/aosp-on-xperia-open-devices/guides/aosp-build-instructions/build-aosp-android-13/) very clearly mentions that you have to do this in `fastbootd` instead of `fastboot`:

![image](https://github.com/sonyxperiadev/bug_tracker/assets/2325264/a6a3486c-3175-489a-b916-d4e00cb393b4)

> Flash first super partitions in fastbootd first and other partitions in fastboot afterwards? Or the other way around?
Any help is greatly appreaciated.

`flashall` does it the other way around (I could go into the technical explanation why, but it seems that would only further confuse your attempts to flash your device), but for your convenience you should do everything from within `fasbootd` as mentioned by @jerpelea.
